BH-982: specify media types for media input
wpengine/atlas-content-modeler pull request #149
Opened 2021-06-15 13:20 UTC by matthewguywright

2021-06-16 11:30 UTC, nickcernis reviewed
This is looking great, @matthewguywright! Nice work.

I'm ok to defer restricting uploadable file types for now if the team is happy with that. From Slack it looks like we'd have to build a custom component to restrict upload types. I think it's enough to restrict file types in the media picker so other types cannot be selected, as you've done here.

The acceptance criteria say, “…publishers receive helpful feedback about accepted media types…”.

Right now they can't really tell what types are accepted and have to figure it out from what appears in the media picker. If no files are in the media area they won't know what types are accepted.

**Do you think we should provide a clue below the field title in the publisher app to help with this?** Maybe we could list allowed file types (if there are any) on the same line as the “required” field? For example, by editing this line (you will need to pull and merge main to see it):

https://github.com/wpengine/atlas-content-modeler/blob/e9becf67924f7fd9c49cec30154c6694d5f8e782/includes/publisher/js/src/components/MediaUploader.jsx#L67

So users would see something like:

```
*Required. Accepts file types: png, jpg, jpeg.
```

Another place we could display it is the Media picker title bar:

<img width="409" alt="Screenshot 2021-06-16 at 13 54 14" src="https://user-images.githubusercontent.com/647669/122214857-dfd56b00-ceaa-11eb-86f8-1165f1a90057.png">

<img width="481" alt="Screenshot 2021-06-16 at 13 54 06" src="https://user-images.githubusercontent.com/647669/122214861-e1069800-ceaa-11eb-8cee-1f30bcfe4754.png">

For example:

```diff
diff --git a/includes/publisher/js/src/components/MediaUploader.jsx b/includes/publisher/js/src/components/MediaUploader.jsx
index db45c3a..c5e5798 100644
--- a/includes/publisher/js/src/components/MediaUploader.jsx
+++ b/includes/publisher/js/src/components/MediaUploader.jsx
@@ -79,8 +79,17 @@ export default function MediaUploader({ modelSlug, field, required }) {
 			library.type = getAllowedTypesLongExtension();
 		}
 
+		const getMediaModalTitle = () => {
+			const title = mediaUrl ? "Change Media" : "Upload Media";
+			if (allowedTypes) {
+				return `${title}  (${allowedTypes.split(",").join(", ")})`;
+			}
+
+			return title;
+		};
+
 		const media = wp.media({
-			title: mediaUrl ? "Change Media" : "Upload Media",
+			title: getMediaModalTitle(),
 			multiple: false,
 			frame: "select",
 			library: library,
```

Adding labels like these also gives us an easier way of writing e2e tests that check that changes made in the developer app affect the publisher app.

2021-06-23 15:47 UTC, ChrisWiegman requested changes
Found some more i18n issues that need addressing (sorry, realize this wasn't in place when you started the PR but we do need to keep these up to date going forward)

2021-06-24 16:12 UTC, ChrisWiegman submitted a review, later dismissed

2021-06-25 15:41 UTC, nickcernis approved these changes, later dismissed

2021-06-25 15:52 UTC, mindctrl approved these changes

2021-06-25 17:19 UTC, mindctrl requested changes, later dismissed
Just realized this doesn't have tests.

2021-06-28 12:37 UTC, mindctrl commented on includes/settings/js/src/components/fields/AdvancedSettings.jsx
> +					{__("Wordpress Allowed Types", "atlas-content-modeler")}
```suggestion
					{__("WordPress Allowed Types", "atlas-content-modeler")}
```

2021-06-29 12:29 UTC, mindctrl commented
Added some tests here. @matthewguywright @nickcernis @ChrisWiegman @anthonyburchell

2021-06-30 10:37 UTC, nickcernis approved these changes
Looking good! Thanks for adding the tests, @mindctrl.

The “Remove Media” button placement can perhaps be improved, but we can fix with any other things flagged in design reviews later: 

<img width="488" alt="Screenshot 2021-06-30 at 12 36 20" src="https://user-images.githubusercontent.com/647669/123946839-f21dd180-d99f-11eb-8747-3a3eb4b19297.png">

2021-07-01 12:16 UTC, mindctrl approved these changes

2021-07-01 12:17 UTC, merged