BH-1053: icon picker using jquery
wpengine/atlas-content-modeler pull request #176
Opened 2021-06-23 15:19 UTC by matthewguywright

2021-06-23 15:44 UTC, ChrisWiegman requested changes
The i18n strings need translation. I'm a little concerned about DRY in the icon list but I'm not even sure anything can be done about that.

2021-06-23 15:44 UTC, ChrisWiegman commented on includes/settings/js/src/components/CreateContentModel.jsx
> +							Choose an icon to represent your model.
These should be translatable.

2021-06-23 15:44 UTC, ChrisWiegman commented on includes/settings/js/src/components/CreateContentModel.jsx
> +											An icon is required
i18n here too (I'll stop calling these out individually but all strings should be ready for i18n)

2021-06-23 15:44 UTC, ChrisWiegman commented on includes/settings/js/src/components/IconPicker.jsx
> +	"",
Is there a reason for the multiple empty options?

Also, is there any easier way to include this array so that it will be easier to maintain as core changes in the future?

2021-06-23 16:07 UTC, matthewguywright commented on includes/settings/js/src/components/IconPicker.jsx
> +	"",
I don't see a programmatic way to include this list. Empty options are removed.

2021-06-23 16:18 UTC, ChrisWiegman approved these changes, later dismissed

2021-06-23 16:18 UTC, ChrisWiegman commented on includes/settings/js/src/components/EditModelModal.jsx
> +							buttonLabel="Choose Icon"
One more (sorry)

2021-06-23 16:18 UTC, ChrisWiegman commented on includes/settings/js/src/components/IconPicker.jsx
> +				'<input type="text" class="" placeholder="Search" />' +
and another i18n

2021-06-23 16:18 UTC, ChrisWiegman commented on includes/settings/vendor/dashicons-picker/dashicons-picker.js
> +						'<input type="text" class="" placeholder="Search" />' +
i18n

2021-06-23 20:29 UTC, ChrisWiegman approved these changes, later dismissed

2021-06-24 11:07 UTC, nickcernis reviewed
This is working really well for me! Some questions/suggestions for improved UX:

1. Should “Choose Icon” say “Change Icon” when an icon has been picked?
2. Should we add a way to remove an icon to restore the default? (Fine if the answer is “no” or if we just add to backlog for now.)
3. The icon picker modal does not gain keyboard focus. (Tab to “Choose icon”, press space to activate the modal, then try tabbing to an icon to choose it without using the mouse.) Is there a way we can fix this? It means the field is not accessible.
4. Are you comfortable writing e2e tests for the icon picker and sidebar?

I think we should also talk about how the “edit model” model isn't scaling very well to hold all of these new options we're adding, but happy to shelve that for a separate time. (Perhaps we should discuss reusing the “New Model” page for Edit Model actions with Mason.)

2021-06-24 12:17 UTC, mindctrl commented
> Should “Choose Icon” say “Change Icon” when an icon has been picked?

👍  nice touch.

> I think we should also talk about how the “edit model” model isn't scaling very well to hold all of these new options we're adding, but happy to shelve that for a separate time. (Perhaps we should discuss reusing the “New Model” page for Edit Model actions with Mason.)

Agreed, I did mention this to Mason on Monday while demoing our latest work. I'll add it to the backlog so he can start thinking about it.

2021-06-24 14:16 UTC, mindctrl commented
@matthewguywright can you bring this up to date with `main`?

2021-06-24 14:38 UTC, mindctrl requested changes
We should add some tests here too.

2021-06-24 16:14 UTC, matthewguywright commented
> We should add some tests here too.

I will need some assistance in how to go about writing tests for this. @mindctrl

2021-06-24 17:22 UTC, matthewguywright commented
@nickcernis @mindctrl I updated based on all the points above. I am going to start working on tests.

2021-06-24 17:42 UTC, mindctrl commented
> I will need some assistance in how to go about writing tests for this.

@matthewguywright we should add some kind of e2e test that confirms the icon picker is on the page and can be used. Once a selection is made and saved, confirm it’s there after saving and that it's used in the sidebar.

Also it'd be nice to have a test for the edit modal functionality to confirm it saves there as well.

We could also add some integration test code to confirm that the CSS and JS assets are enqueued when landing on the page in general, though if it's not the e2e test would fail... but it'd be nice to fail earlier on the faster tests and doing an integration test would help that.

2021-06-25 13:40 UTC, mindctrl commented
This PR makes the edit modal larger than the screen for me, so I can't see the `h2` title.

Since this field was added between API Identifier and API Visibility, it causes both to go full width when they should be side by side. I think moving the icon field `div` below the API Visibility `div`, instead of in between the two API fields, will mostly fix it.

2021-06-25 13:42 UTC, mindctrl requested changes, later dismissed

2021-06-25 13:42 UTC, mindctrl commented on includes/settings/js/src/components/CreateContentModel.jsx
> +							{__("Model Icon", "atlas-content-modeler")}
Let's move this whole field below the API fields. Having so much distance between the Singular Name field and the API Identifier makes it less obvious on smaller screens that the latter is auto-generating as you type in the singular field.

2021-06-25 15:35 UTC, ChrisWiegman requested changes, later dismissed
I did find a bug. On a new model I clicked the "choose icon" button but didn't change it. It then wouldn't let me save it as it wanted me to choose one.

![Screen Shot 2021-06-25 at 11 34 22 AM](https://user-images.githubusercontent.com/394675/123449212-72f85a00-d5a9-11eb-8909-e717f2f96112.png)

2021-06-25 15:40 UTC, mindctrl commented
@ChrisWiegman good catch. I think we can make this field not required since we're supplying a fallback. Thoughts @wpengine/blockheads?

2021-06-25 15:43 UTC, ChrisWiegman commented
I think that's the right approach, @matthewguywright.

2021-06-29 17:06 UTC, mindctrl commented
These codeclimate recommendations are good, but I'm not refactoring Matthew's work in this PR. If we can make it not "fail" on suggestions that would be great. cc: @ChrisWiegman

2021-06-29 17:21 UTC, mindctrl commented on includes/content-registration/custom-post-types-registration.php
> +		'menu_icon'             => $args['modelIcon'] ?? 'dashicons-admin-post',
The camelCase here doesn't match the snake_case we've used elsewhere.

2021-06-29 18:00 UTC, mindctrl commented
Converted to draft until I have a chance to finish converting modelIcon to model_icon where appropriate.

2021-06-30 16:25 UTC, nickcernis commented
@mindctrl Is the default icon sticking for you? For me, I see no icon if I don't choose one:

1. Create a model but don't choose an icon (shows a default of the pin icon).
2. The resulting sidebar row has no icon (on creation, and after refresh).
3. The icon appears as `'model_icon' => '',` in the `atlas_content_modeler_post_types` option.

2021-06-30 16:40 UTC, mindctrl commented
@nickcernis good catch. Pretty sure that was working, but looks like it's not now. I'll take another look.

2021-06-30 17:12 UTC, mindctrl commented
@nickcernis should be fixed in 5b5bf0d7310bf0b5c2a99c819bf6ed9eefdef3f1

2021-06-30 19:12 UTC, nickcernis commented
@mindctrl Working for me when the model is first added now, but the default icon disappears from the sidebar on refresh. 😭  (Sorry not to dig in to discover why just yet — happy to circle back in the morning.)

2021-07-01 11:04 UTC, nickcernis approved these changes

2021-07-01 12:24 UTC, merged