BH-1075 Allow creation of taxonomies in the developer app
wpengine/atlas-content-modeler pull request #183
Opened 2021-06-29 09:30 UTC by nickcernis

Work in progress for taxonomies additions to the settings/developer app.

- Adds a new taxonomies view at `/wp-admin/?page=atlas-content-modeler&view=taxonomies`.
- Adds a “View Taxonomies” button on the main model listings page (for now; this may move later).

### To-do
- [ ] Add taxonomy creation form.
- [ ] Add e2e tests for taxonomy creation.

2021-06-30 14:36 UTC, mindctrl commented on includes/rest-api/rest-api-endpoint-registration.php
> +	}
Nice. We should probably also check for conflicts with existing taxonomies registered via other means (WP core, other plugins, custom code, etc.)

2021-06-30 16:01 UTC, mindctrl commented on includes/rest-api/rest-api-endpoint-registration.php
> + * @return object|WP_Error
```suggestion
 * @return array|WP_Error
```

It looks like `$taxonomy` is an array

2021-06-30 16:26 UTC, nickcernis commented on includes/rest-api/rest-api-endpoint-registration.php
> + * @return object|WP_Error
Good catch, thanks — not sure why PhpStorm didn't infer that. 🤷

2021-06-30 16:40 UTC, nickcernis commented on includes/rest-api/rest-api-endpoint-registration.php
> +	}
Good idea. I think this should cover it: https://github.com/wpengine/atlas-content-modeler/pull/183/commits/3fadd02e8e940c2fa050af854c8dda2ee68e1f47.

2021-06-30 17:34 UTC, mindctrl requested changes
Overall working well! Just a few comments.

2021-06-30 17:34 UTC, mindctrl commented on includes/settings/js/src/components/Taxonomies.jsx
> +import { toValidApiId } from "./fields/toValidApiId";
```suggestion

```
Looks like this is not used now.

2021-06-30 17:34 UTC, mindctrl commented on includes/settings/js/src/components/Taxonomies.jsx
> +										maxLength: 20,
```suggestion
										maxLength: 32,
```

`register_taxonomy` supports 32 chars here and we went with that in the schema def here: https://github.com/wpengine/atlas-content-modeler/blob/ab37aad2c043603e2d6b86319fa29b567750a163/docs/adr/0002-taxonomy-definition-schema.md

2021-06-30 17:34 UTC, mindctrl commented on includes/settings/js/src/components/Taxonomies.jsx
> +														"Exceeds max length of 20.",
```suggestion
														"Exceeds max length of 32",
```

to match above suggestion

2021-06-30 18:04 UTC, mindctrl approved these changes

2021-06-30 21:52 UTC, apmatthews reviewed
Just one minor comment, but works well otherwise!

2021-06-30 21:52 UTC, apmatthews commented on includes/settings/js/src/components/Taxonomies.jsx
> +					setApiIdGeneratorInput(""); // Resets the API ID field.
We also need to run `setSingularCount(0)` and `setPluralCount(0)` as part of the reset.

2021-07-01 07:58 UTC, nickcernis commented on includes/settings/js/src/components/Taxonomies.jsx
> +					setApiIdGeneratorInput(""); // Resets the API ID field.
Thank you, well spotted! Fixed in 76b2e04.

2021-07-01 08:05 UTC, merged