Update "API Identifer" to "Model ID" with associated desc.
wpengine/atlas-content-modeler pull request #200
Opened 2021-07-21 16:27 UTC by ChrisWiegman

## Description

https://wpengine.atlassian.net/browse/

## Testing

## Screenshots

## Documentation Changes

## Dependant PRs

2021-07-21 22:19 UTC, apmatthews requested changes
I think we want to keep "API Identifier" anywhere that it's used to describe the slug of a user-defined "field" (in `Form.jsx` for example). It's accurately worded in that context since we pass the value to REST and WPGraphQL.

2021-07-22 08:58 UTC, nickcernis commented
> I think we want to keep "API Identifier" anywhere that it's used to describe the slug of a user-defined "field"

Agreed, it only needs to change for the new model and edit model forms.

2021-07-22 13:20 UTC, ChrisWiegman commented
Thanks. This is good to know as I can't deny I don't understand where these all are actually used in context. I've redone the PR with only the changes to the two forms.

2021-07-22 13:30 UTC, nickcernis approved these changes, later dismissed
Looks great! Thanks for grabbing this one, @ChrisWiegman.

2021-07-22 13:33 UTC, mindctrl approved these changes, later dismissed

2021-07-22 13:39 UTC, apmatthews commented
A couple of instances we do want changed were reverted. See the `create_model()` function error messages.

<img width="475" alt="Screen Shot 2021-07-22 at 9 34 49 AM" src="https://user-images.githubusercontent.com/4661832/126648013-bbc41dcc-a495-4c7f-9147-0828522126ae.png">

2021-07-22 13:50 UTC, ChrisWiegman commented
Good catch Andrew. I had manually changed the field but hadn't reproduced an error.
![Screen Shot 2021-07-22 at 9 48 14 AM](https://user-images.githubusercontent.com/394675/126650111-588fcdc6-2aa9-466b-bc07-7332c8933913.png)

2021-07-22 13:51 UTC, apmatthews approved these changes

2021-07-22 13:54 UTC, mindctrl approved these changes

2021-07-22 14:02 UTC, nickcernis approved these changes

2021-07-22 14:35 UTC, merged