BH-1103: re deploy of branch
wpengine/atlas-content-modeler pull request #202
Opened 2021-07-22 14:40 UTC by matthewguywright

## Description

https://wpengine.atlassian.net/browse/

## Testing

## Screenshots

## Documentation Changes

## Dependant PRs

2021-07-22 14:53 UTC, mindctrl commented
Linking to comment on the previous PR: https://github.com/wpengine/atlas-content-modeler/pull/199#issuecomment-884882727

2021-07-22 17:27 UTC, ChrisWiegman submitted a review, later dismissed

2021-07-22 21:20 UTC, anthonyburchell commented
I noticed that you are able to use `.0` in integer fields. 

to reproduce, create a new field set to integer and enter `5.0` for the value. This is the same as `5` technically, but I wonder if the decimal will trip folks up on the front end.

2021-07-22 21:33 UTC, anthonyburchell commented
Could we potentially do an `onChange` to just not allow decimals to be entered in integer number fields?

2021-07-23 13:23 UTC, mindctrl commented
@matthewguywright nice fix on the decimals getting cut off on the error message.

Something @apmatthews said yesterday is worth considering... https://github.com/wpengine/atlas-content-modeler/pull/199#discussion_r674339038

Let me show an example:
Number field, configured as Integer, advanced settings as follows: min: -5, max: 25, step: 5

On publisher side, if someone enters "2" in this field, the error message says "Step value is 5", which is confusing and helpful to understand what type of values can be entered.

Screenshot
![image](https://user-images.githubusercontent.com/1254870/126787870-74e78564-bf82-42ad-8b6b-5d8cd15c2a86.png)

Thoughts on how to address this in a way that's easy for users to understand? We can do this in another PR if we want more time to think it through.

2021-07-26 11:54 UTC, mindctrl commented
@matthewguywright this seems to be working well now. Can you add some e2e tests that confirm the desired behavior?

2021-07-27 13:04 UTC, ChrisWiegman requested changes
This seems to work for me. Only issue is a string that is missing i18n.

2021-07-27 13:04 UTC, ChrisWiegman commented on includes/publisher/js/src/components/Field.jsx
> +				error = "The input is invalid.";
This needs to be translatable.

2021-07-27 14:39 UTC, matthewguywright commented on includes/publisher/js/src/components/Field.jsx
> +				error = "The input is invalid.";
Updated

2021-07-27 18:44 UTC, ChrisWiegman submitted a review, later dismissed

2021-07-28 13:26 UTC, mindctrl requested changes

2021-07-28 13:26 UTC, mindctrl commented on tests/acceptance/PublishModelCest.php
> +	public function error_is_triggered_for_invalid_value(\AcceptanceTester $i)
@matthewguywright let's rename these test methods to something more descriptive and related to the number field things they're testing. Example: `i_see_submission_errors_in_number_fields_when_input_is_invalid_for_the_number_type` or something along those lines.

2021-07-28 13:26 UTC, mindctrl commented on includes/publisher/js/src/components/Field.jsx
> +				error = __("The input is invalid.", "atlas-content-modeler");
Can we make this error message clearer? Can we tell the user why it's invalid?

2021-08-02 13:36 UTC, mindctrl commented on tests/acceptance/PublishModelCest.php
> +		$i->haveContentModel('moose', 'mooses', 'Mooses go frmh');
It'd be nice to not change these tests from goose to moose. I know that came about due to local test failures, where the content models weren't being wiped out between tests, but I think we are addressing that another way.

2021-08-02 14:23 UTC, matthewguywright commented on tests/acceptance/PublishModelCest.php
> +		$i->haveContentModel('moose', 'mooses', 'Mooses go frmh');
Updated

2021-08-02 14:32 UTC, mindctrl commented
@matthewguywright if you bring this up to date with `main` the failing unit tests should pass.

2021-08-02 15:29 UTC, anthonyburchell submitted a review, later dismissed
Awesome stuff! Great workarounds to the edge cases! LGTM 👍

2021-08-02 15:41 UTC, mindctrl commented on tests/acceptance/PublishModelCest.php
> +		$i->haveContentModel('goose', 'gooses', 'gooses go frmh');
```suggestion
		$i->haveContentModel('goose', 'geese', 'Geese go honk');
```

...to get it back to what it was before... gooses? :laughing:

2021-08-02 16:36 UTC, mindctrl commented on tests/acceptance/PublishModelCest.php
> +		$i->see('This field is required');
@matthewguywright I wonder if we should test a scenario where the field is not required? The Jira issue described a case where the "This field is required" message showed when it should not. A test that confirms this would catch any regressions for that specific bug.

2021-08-02 18:30 UTC, matthewguywright commented on tests/acceptance/PublishModelCest.php
> +		$i->see('This field is required');
Haha. Updated.

2021-08-02 19:14 UTC, anthonyburchell approved these changes
Nice callout on that test case @mindctrl ! Looks good to me! :D

2021-08-02 20:17 UTC, mindctrl approved these changes

2021-08-02 20:24 UTC, merged