Allow Developers to change option names
wpengine/atlas-content-modeler pull request #210
Opened 2021-07-29 05:30 UTC by anthonyburchell

## Description

This PR adds multiple choice fields back into ACM and adds better validation and a data structure that allows for content model creators to change choice names. The key value way we're storing them now should ensure that the slug is maintained and the name is dynamic.

2021-08-02 20:47 UTC, matthewguywright commented on includes/publisher/js/src/components/Field.jsx
> +													Object.keys(slug) ==
=== vs ==

2021-08-02 20:50 UTC, matthewguywright commented on includes/settings/js/src/components/fields/MultipleChoiceFields.jsx
> +										className={`choices[${index}].container field multiple-option-container-single`}
That's an interesting class name. Do we want '.'s in the class name? Like would this be something like:
choices[1].container field ...

Or is this a WP standard thing?

2021-08-02 20:53 UTC, matthewguywright commented on includes/settings/js/src/components/fields/Form.jsx
> +				if (err.code === "wpe_option_slug_undefined") {
It would be nice to see these errors broken out into a separate object or an enum and use a switch statement or external function instead. There are quite a few of these now.

2021-08-02 21:59 UTC, anthonyburchell commented on includes/settings/js/src/components/fields/MultipleChoiceFields.jsx
> +										className={`choices[${index}].container field multiple-option-container-single`}
it surprisingly works, but yeah I think we could switch these to `-` between each word. `choices-1-container`

2021-08-03 11:47 UTC, nickcernis commented on includes/settings/js/src/components/fields/MultipleChoiceFields.jsx
> +										className={`choices[${index}].container field multiple-option-container-single`}
If we're using that class only as a selector for the “remove choice” e2e test, another option is to:

1. Remove the className here:

```suggestion
										className={`field multiple-option-container-single`}
```
2. Change the test selector:

```diff
diff --git a/tests/acceptance/CreateContentModelMultipleChoiceFieldCest.php b/tests/acceptance/CreateContentModelMultipleChoiceFieldCest.php
index 3fc3613..26fe3f3 100644
--- a/tests/acceptance/CreateContentModelMultipleChoiceFieldCest.php
+++ b/tests/acceptance/CreateContentModelMultipleChoiceFieldCest.php
@@ -28,7 +28,7 @@ class CreateContentModelMultipleChoiceFieldCest
         $I->wait(1);
         $I->seeInField('choices[0].name', 'dog');
         $I->see('Editing “Favorite Animal” Field', '.field-list');
-        $I->click('.remove-option', '.choices[0].container');
+        $I->click('Remove choice');
         $I->wait(1);
         $I->seeInField('choices[0].name', 'cat');
     }
```

The test runner will click the first button with the “Remove choice” text, which is the same button that was previously identified by `choices[0].container`.

2021-08-03 12:17 UTC, nickcernis commented on includes/settings/js/src/components/fields/MultipleChoiceFields.jsx
> +import { toValidApiId } from "./toValidApiId";
Just a heads up that Andrew's PR at https://github.com/wpengine/atlas-content-modeler/pull/214 changes the location of `toValidApiId`. (Just something to look out for in case that PR is merged first.)

2021-08-03 12:23 UTC, nickcernis commented
This is working well for me!

Apart from the above comments, I noticed that the `multipleChoice` field does not appear in WPGraphQL responses (I think because no type in `map_html_field_type_to_graphql_field_type` or resolver in `register_content_fields_with_graphql` are configured).

That might need to be a separate PR before we can ship this. (Unless we want to ship without WPGraphQL support and add it later?) REST support looks ok to me.

2021-08-03 23:16 UTC, apmatthews commented on includes/publisher/lib/field-functions.php
> +					$options_object[] = $option;
I may be totally missing something, but does this block actually change the value? The way it's written, I'm wondering if we need the `is_array()` conditional at all.

If we do want to transform this value somehow when it's an array, should we keep the `key()` function there as it was? Otherwise, we'll be saving option names. For instance, this is what would be saved for a multi-select field:

```
a:2:{i:0;a:1:{s:3:"two";s:3:"Two";}i:1;a:1:{s:5:"three";s:5:"Three";}}
```

(Unrelated to this PR, but it looks like we don't even use the value that gets returned from the `sanitize_field()` function 😬. I'll make a note to follow up on that!)

2021-08-04 07:23 UTC, nickcernis commented on includes/publisher/lib/field-functions.php
> +					$options_object[] = $option;
I agree that we could remove or adapt it. It was left when Repeater fields were removed:

- https://github.com/wpengine/atlas-content-modeler/pull/124#pullrequestreview-671211033
- https://github.com/wpengine/atlas-content-modeler/pull/124#issuecomment-850533862

2021-08-04 13:27 UTC, mindctrl commented
When adding this field to a model, the cursor focus goes to the name input for Choice 1, skipping the Field name input which appears first.

![image](https://user-images.githubusercontent.com/1254870/128188775-4ed7cd23-41ed-4cf7-9917-6e53fc38b538.png)

2021-08-09 16:58 UTC, nickcernis commented on includes/publisher/js/src/components/Field.jsx
> +										value={item.name}
Agreed, good catch.

2021-10-25 09:01 UTC, nickcernis reviewed
@anthonyburchell I'm currently unable to create a multiple choice field. I see “Must create a choice first” when clicking Create, even after creating choices:

<img width="870" alt="Screenshot 2021-10-25 at 10 57 49" src="https://user-images.githubusercontent.com/647669/138666353-83089a04-e35c-4912-9d37-30356a2adf4a.png">

Guessing that may be responsible to some of the e2e test failures on this branch?

I left another comment above about one of Andrew's suggestions, and dismissed some stale comments.

2021-10-27 15:22 UTC, ChrisWiegman reviewed
We've chatted about this elsewhere but I feel it is important to bring it here before I approve this.

What about hiding the slug field for each choice? We're not using them in GraphQL and the requirement to create one manually is strange and confusing in the settings app. I feel we would be better serving users by autogenerating that in the background. How we do that, here or another ticket, is something I'm more than willing to discuss.

2021-10-27 15:29 UTC, ChrisWiegman submitted a review, later dismissed
Beyond the comments, I would like to see some tests for a GraphQL response (where appropriate).

2021-11-05 20:46 UTC, mindctrl requested changes

2021-11-05 20:47 UTC, mindctrl commented
@anthonyburchell can you bring this up to date with `main`? Looks like quite a few things are missing, like recent Parcel fixes.

2021-11-15 20:04 UTC, mindctrl commented
Given a model like this screenshot:
![image](https://user-images.githubusercontent.com/1254870/141845890-b599903a-e18a-4600-920e-1d78bef7ea92.png)

---

And adding an entry like this screenshot:
![image](https://user-images.githubusercontent.com/1254870/141845937-5507715d-2619-4eac-a194-6be1d0b61d03.png)

---

Results in the meta value being stored like this:
`a:1:{i:0;a:1:{s:10:"greenBeans";s:10:"greenBeans";}}`

Does this seem right? Do we need to store the value twice for each selection? If I add another selection, the value looks like this:
`a:2:{i:0;a:1:{s:10:"greenBeans";s:10:"greenBeans";}i:1;a:1:{s:4:"rice";s:4:"rice";}}`

2021-11-16 16:34 UTC, matthewguywright commented
General Notes:

1. Remove choice is awkward, especially in smaller screen resolutions for tablets and smaller. Is the text necessary? Can it use just the red trash can or a red "x"?
2. Currently it doesn't auto generate the identifier
3. Character count for "Name" field is misaligned with the input
4. Label not aligned vertically in publisher with the radio and checkbox input
5. Legend label looks indented by 2px from the rest of the form

2021-11-18 10:39 UTC, nickcernis commented on includes/rest-api/routes/content-model-field.php
> +				'Another choice in this field has the same API identifier.',
Confirmed fixed in 44440f7c30a81f1d4045b153a22a8075f2e4bb2a.

2021-11-18 10:39 UTC, nickcernis commented on includes/rest-api/routes/content-model-field.php
> +				'Another choice in this field has the same name.',
Confirmed fixed in 44440f7c30a81f1d4045b153a22a8075f2e4bb2a.

2021-11-18 10:39 UTC, nickcernis commented on includes/rest-api/routes/content-model-field.php
> +				'Multiple Choice Field update failed, please set a slug for your choice before saving.',
Confirmed fixed in 44440f7c30a81f1d4045b153a22a8075f2e4bb2a.

2021-11-18 15:04 UTC, mindctrl submitted a review, later dismissed

2021-11-18 15:39 UTC, mindctrl commented on includes/settings/js/src/components/fields/Form.jsx
> +				if (err.code === "wpe_option_slug_undefined") {
Agreed, but I think we can tackle that in the future.

2021-11-18 15:41 UTC, mindctrl commented on includes/rest-api/routes/content-model-field.php
> +			__( 'Multiple Choice update failed. Options need to be created before updating a Multiple Choice field.', 'atlas-content-modeler' ),
```suggestion
			__( 'Multiple Choice update failed. Choices need to be created before updating a Multiple Choice field.', 'atlas-content-modeler' ),
```

Should we say "Choices" instead of "Options" here, since the UI calls them choices?

2021-11-23 17:36 UTC, nickcernis commented on includes/settings/js/src/components/fields/MultipleChoiceFields.jsx
> +															"atlas-content-modeler"
I agree with this, but perhaps to keep the PR on track we could handle updating error message handling in a separate PR? There are some other places we should change it, as @anthonyburchell noted in standup.

2021-11-25 09:22 UTC, nickcernis commented on includes/rest-api/routes/content-model-field.php
> +			$problem_duplicate_name->add( 'problem_name_index', $problem_name_index );
Addressed in 866bbfb35be5dcc76f7d21d029279fc8d43f9935 and 2543ab9dc6c5a98e8aa98dcba9c86c513a3a4518.

2021-11-25 12:43 UTC, nickcernis submitted a review, later dismissed
Looks good! 🥳 

Noting that we chose not to auto-generate the choice slugs from their names for now. (This requires a refactor of the `useInputGenerator` hook to support dynamically sized arrays of inputs, which seems out of scope for now.)

2021-11-29 16:31 UTC, nickcernis approved these changes

2021-11-29 16:46 UTC, mindctrl approved these changes

2021-11-29 16:58 UTC, merged