BH-1156 BH-1157 Google Analytics
wpengine/atlas-content-modeler pull request #243
Opened 2021-08-19 17:45 UTC by matthewguywright

## Description
Google analytics in place for ACM and Publisher.

2021-08-19 17:46 UTC, matthewguywright commented on includes/shared-assets/js/ga-analytics.js
> +ga("create", "281125716", "auto");
I got this from GA for ACM. Is this the correct number? 281125716

2021-08-19 17:46 UTC, matthewguywright commented on includes/publisher/class-publisher-form-editing-experience.php
@ChrisWiegman @mindctrl I don't think I have permission to do anything with the filters. I see one for excluding internal traffic but it's greyed out for me. That's for the IP Address blocking.

2021-08-19 17:48 UTC, matthewguywright commented on includes/publisher/class-publisher-form-editing-experience.php
> +		wp_register_script(
@mindctrl I think these two enqueue's can be in the shared_assets.php file right? Just in one place. That's where the banner is included. Thoughts? Then we won't have duplicate code.

2021-08-19 19:56 UTC, mindctrl requested changes

2021-08-19 19:56 UTC, mindctrl commented on includes/publisher/class-publisher-form-editing-experience.php
> +			'google-analytics',
This needs to be a name unique to our plugin.

2021-08-19 19:56 UTC, mindctrl commented on includes/publisher/class-publisher-form-editing-experience.php
> +		wp_enqueue_script( 'google-analytics' );
Related to above, this needs to be a name unique to our plugin.

2021-08-19 19:56 UTC, mindctrl commented on includes/publisher/class-publisher-form-editing-experience.php
> +		wp_register_script(
@matthewguywright yes you can register the script in the shared file, and then enqueue it where necessary.

2021-08-19 20:16 UTC, mindctrl commented on includes/shared-assets/js/ga-analytics.js
> +ga("create", "281125716", "auto");
I think you need the UA number? https://developers.google.com/analytics/devguides/collection/analyticsjs

2021-08-20 14:14 UTC, matthewguywright commented on includes/shared-assets/js/ga-analytics.js
> +ga("create", "281125716", "auto");
There isn't a UA number in Analytics that I can find. I followed a guide to find it and where theirs shows a UA number, ours shows the number above. Thoughts? Can you confirm? https://ryanmilani.com/sem-blog/data-analytics/quickly-find-ua-code/

2021-08-20 16:02 UTC, ChrisWiegman submitted a review, later dismissed
I can confirm pageviews are firing and appear to only be doing so in settings and publisher pages. LGTM

2021-08-23 13:03 UTC, mindctrl requested changes

2021-08-23 13:03 UTC, mindctrl commented on includes/shared-assets/wp_scripts/shared_assets.php
> +	);
I think we should register the script here, like the one below it is, and then enqueue it the same where needed. Otherwise this loads on all admin pages, even when it's not needed.

2021-08-23 13:06 UTC, mindctrl commented
Note to selves: this shouldn't be merged into `main` until we have official guidance from legal.

2021-08-23 15:31 UTC, nickcernis commented on includes/publisher/js/src/App.jsx
> + *	});
Suggest removing ReactGA example docs, which could change (but maintaining the link to their readme).

2021-08-23 15:31 UTC, nickcernis commented on includes/settings/js/src/App.jsx
> + *	});
Same here — we probably don't need to inline these docs.

2021-08-23 15:36 UTC, nickcernis commented on includes/publisher/js/src/App.jsx
> +	ReactGA.send({ hitType: "pageview", page: "Publisher App Home" });
What do you think of this? (The publisher app doesn't really have a “Home”, but if the publisher app loads the user is viewing a publisher entry.)

```suggestion
	ReactGA.send({ hitType: "pageview", page: "ACM Publisher Entry" });
```

2021-08-23 15:46 UTC, mindctrl commented on includes/settings/js/src/App.jsx
> +		page: "ACM Settings Home",
"Settings" is something I've been thinking about lately. We first started out this project by copying an existing 'settings' admin page from the headless plugin. There we had legit settings, here not so much.

As the devex side of our app has evolved to include many "pages", like models and taxonomies, I wonder if it's time to start referencing this by another name?

Think of this, if we later have an actual settings page, the page view data could get skewed if we report them as the same page. I wonder if we should make the distinction now? "ACM Models Home" or something similar, and then have "ACM Taxonomies Home" (or whatever) for that view. I think it would be helpful to distinguish between them. And then it naturally leads to other events like "Editing taxonomy", "Editing model", or similar. Thoughts?

2021-08-23 15:47 UTC, nickcernis commented on includes/settings/js/src/App.jsx
> +		page: "ACM Settings Home",
"ACM Models Home" makes sense to me.

2021-08-26 15:47 UTC, closed without merging