Feature/metadata
wpengine/atlas-content-modeler pull request #253
Opened 2021-08-26 18:42 UTC by matthewguywright

## Description

In progress draft PR for metadata.

2021-08-26 20:31 UTC, mindctrl requested changes

2021-08-27 14:50 UTC, ChrisWiegman requested changes
The generic events are great. What worries me here is the disclosure of "what" they're building (see screenshots below). We may need to kill pageviews. We should never know what they call something, just that they're building something.

![Screen Shot 2021-08-27 at 10 29 36](https://user-images.githubusercontent.com/394675/131146095-46f00ee0-7b89-44d7-9503-d60c5895c616.png)
![Screen Shot 2021-08-27 at 10 29 46](https://user-images.githubusercontent.com/394675/131146101-abe1f05c-ea79-4cf2-8ad7-690692cd1e9c.png)
![Screen Shot 2021-08-27 at 10 30 24](https://user-images.githubusercontent.com/394675/131146104-d7c2d30a-9637-4af5-939e-50076d23007c.png)

2022-01-13 20:00 UTC, mindctrl commented on includes/settings/js/src/components/DeleteModelModal.jsx
> +								if (atlasContentModeler.usageTrackingEnabled) {
I don't love adding this kind of logic everywhere we want an event. An alternative is to put the logic inside the functions that send the events. However, the `usageTrackingEnabled` bit that is passed through `wp_localize_script` is done for two separate scripts (publisher and settings) and exposed through two different global variables by WP. We don't have a single shared script that is enqueued and localized in both places. Something to consider for the near future.

2022-01-13 20:11 UTC, mindctrl commented
This is ready for a preliminary review. I updated the original post with the remaining tasks.

2022-01-14 13:34 UTC, nickcernis commented on includes/settings/js/src/components/DeleteModelModal.jsx
> +								if (atlasContentModeler.usageTrackingEnabled) {
@mindctrl Perhaps something like this for now?

```diff
diff --git a/includes/shared-assets/js/analytics.js b/includes/shared-assets/js/analytics.js
index dfa17c6..7332f8b 100644
--- a/includes/shared-assets/js/analytics.js
+++ b/includes/shared-assets/js/analytics.js
@@ -7,6 +7,10 @@ import ReactGA from "react-ga4";
 
 const ANALYTICS_ID = "G-S056CLLZ34";
 
+const telemetryEnabled =
+	atlasContentModelerFormEditingExperience?.usageTrackingEnabled ||
+	atlasContentModeler?.usageTrackingEnabled;
+
 const maybeInitializeAnalytics = () => {
 	if (!ReactGA?.isInitialized) {
 		ReactGA.initialize(ANALYTICS_ID, {
@@ -17,13 +21,18 @@ const maybeInitializeAnalytics = () => {
 
 export const sendEvent = (data) => {
 	maybeInitializeAnalytics();
-	return ReactGA.event(data);
+	if (telemetryEnabled) {
+		return ReactGA.event(data);
+	}
 };
 
 export const sendPageView = (page = "") => {
 	maybeInitializeAnalytics();
-	return ReactGA.send({
-		hitType: "pageview",
-		page,
-	});
+
+	if (telemetryEnabled) {
+		return ReactGA.send({
+			hitType: "pageview",
+			page,
+		});
+	}
 };
```

2022-01-14 14:20 UTC, nickcernis commented on includes/settings/js/src/components/Settings.jsx
> +export default function Settings() {
This isn't saving settings quite right for me at the moment:

- Disabled isn't active by default (i.e. when `atlas_content_modeler_usage_tracking` is empty).
- Clicking 'disabled' then refreshing shows no option as active.

This change seems to fix both issues:

```diff
diff --git a/includes/settings/js/src/components/Settings.jsx b/includes/settings/js/src/components/Settings.jsx
index bdaff70..77635d6 100644
--- a/includes/settings/js/src/components/Settings.jsx
+++ b/includes/settings/js/src/components/Settings.jsx
@@ -8,12 +8,12 @@ export default function Settings() {
 		atlasContentModeler.usageTrackingEnabled
 	);
 
-	function saveUsageTrackingSetting(event) {
+	function saveUsageTrackingSetting(value) {
 		// @todo catch save errors
 		dispatch("core").saveSite({
-			atlas_content_modeler_usage_tracking: event.target.value,
+			atlas_content_modeler_usage_tracking: value,
 		});
-		setUsageTracking(event.target.value);
+		setUsageTracking(value);
 	}
 
 	return (
@@ -51,10 +51,13 @@ export default function Settings() {
 													name="atlas-content-modeler-settings[usageTracking]"
 													value="0"
 													checked={
-														usageTracking === "0"
+														usageTracking === "0" ||
+														!usageTracking
 													}
-													onChange={
-														saveUsageTrackingSetting
+													onChange={() =>
+														saveUsageTrackingSetting(
+															"0"
+														)
 													}
 												></input>
 												{__(
@@ -70,8 +73,10 @@ export default function Settings() {
 												name="atlas-content-modeler-settings[usageTracking]"
 												value="1"
 												checked={usageTracking === "1"}
-												onChange={
-													saveUsageTrackingSetting
+												onChange={() =>
+													saveUsageTrackingSetting(
+														"1"
+													)
 												}
 											></input>
 											<label
```

2022-01-14 14:24 UTC, nickcernis commented on includes/settings/js/src/components/Settings.jsx
> +													}
This isn't saving settings quite right for me at the moment:

- Disabled isn't active by default (i.e. when atlas_content_modeler_usage_tracking is empty).
- Clicking 'disabled' then refreshing shows no option as active.

This change seems to fix both issues:

```suggestion
													checked={
														usageTracking === "0" ||
														!usageTracking
													}
```

2022-01-17 11:16 UTC, nickcernis commented on includes/settings/js/src/components/DeleteModelModal.jsx
> +import { sendEvent } from "../../../../shared-assets/js/analytics";
Worth using the alias here for consistency?

```suggestion
import { sendEvent } from "acm-analytics";
```

2022-01-17 11:21 UTC, nickcernis approved these changes, later dismissed
One suggestion above but otherwise looks good! Might also benefit from a changelog entry under "Unreleased"?

2022-01-18 13:57 UTC, mindctrl commented on includes/settings/js/src/components/DeleteModelModal.jsx
> +import { sendEvent } from "../../../../shared-assets/js/analytics";
Ah yes, I think my editor auto-added the path. Good catch.

2022-01-18 14:24 UTC, nickcernis commented on CHANGELOG.md
> +- Opt-in anonymous usage tracking to help us make Atlas Content Modeler better.
Worth adding this for clarification?

```suggestion
- Opt-in anonymous usage tracking to help us make Atlas Content Modeler better (disabled by default).
```

2022-01-18 14:29 UTC, mindctrl commented on CHANGELOG.md
> +- Opt-in anonymous usage tracking to help us make Atlas Content Modeler better.
Definitely! Thanks!

2022-01-18 14:31 UTC, nickcernis submitted a review, later dismissed

2022-01-19 14:16 UTC, nickcernis submitted a review, later dismissed

2022-01-20 08:49 UTC, nickcernis approved these changes

2022-01-20 17:54 UTC, merged