BH-1197: import/export
wpengine/atlas-content-modeler pull request #274
Opened 2021-09-15 16:04 UTC by matthewguywright

## Description

Import/Export main feature branch.

2021-09-15 19:08 UTC, mindctrl requested changes

2021-09-15 19:08 UTC, mindctrl commented on includes/settings/js/src/components/Tools.jsx
> +								<button className="button button-primary link-button">
Looks like button styles are off? You see same?

What I see:
![image](https://user-images.githubusercontent.com/1254870/133494341-7cdc96b9-d144-4e55-bcd2-ec72184728bb.png)

Should look like:

![image](https://user-images.githubusercontent.com/1254870/133494375-18771496-8772-4747-b363-b40ed80c617d.png)

2021-09-15 19:08 UTC, mindctrl commented on includes/settings/js/src/components/Tools.jsx
> +					toast(
The toast design looks off to me. Here's what I see:

![image](https://user-images.githubusercontent.com/1254870/133494585-15d962a0-d3d9-4bba-850c-9d1b07cfe716.png)

2021-09-16 15:23 UTC, matthewguywright commented on includes/settings/js/src/components/Tools.jsx
> +					toast(
This has been updated.

2021-09-16 15:35 UTC, matthewguywright commented on includes/settings/js/src/components/Tools.jsx
> +								<button className="button button-primary link-button">
Updated.

2021-09-16 16:38 UTC, mindctrl requested changes

2021-09-16 16:38 UTC, mindctrl commented on includes/settings/js/src/components/Tools.jsx
> +										"Import Model",
```suggestion
										"Import Models",
```

I know the mocks show singular, but it's more accurate to use plural.

2021-09-16 16:38 UTC, mindctrl commented on includes/settings/js/src/components/Tools.jsx
> +										"Export Model",
```suggestion
										"Export Models",
```

Same as above.

2021-09-16 16:38 UTC, mindctrl commented on includes/settings/js/src/components/Tools.jsx
> +										"Exporting a model will generate a .json document representing all of the existing models and fields.",
```suggestion
										"Exporting models will generate a .json document representing all of the existing models and fields.",
```

2021-09-16 16:38 UTC, mindctrl commented on includes/settings/js/src/components/Tools.jsx
> +										"Select a .json file containing model/field definitions to import as a content model.",
```suggestion
										"Select the .json file containing model/field definitions to be imported.",
```

2021-09-16 16:38 UTC, mindctrl commented on includes/settings/js/src/components/Tools.jsx
> +									fileTitle={`${getFormattedDateTime()}-model-export.json`}
I think we should include something here that identifies the file came from ACM. Something like `acm-models-export-DATETIME.json` or `atlas-content-modeler-models-export-DATETIME.json`

Also I think it helps to put the datetime at the end, so the filename "reads" more like a short sentence.

2021-09-16 16:38 UTC, mindctrl commented on includes/settings/scss/_buttons.scss
> +		border: 1px solid lighten($color-blue-dark, 10%) !important;
Can we make it so `!important` isn't required here? These are starting to creep more and more into our styles.

2021-09-20 09:35 UTC, nickcernis commented on includes/settings/js/src/components/Tools.jsx
> +									fileTitle={`${getFormattedDateTime()}-model-export.json`}
I like `acm-models-export-DATETIME.json`.

2021-09-20 09:51 UTC, nickcernis commented on includes/settings/js/src/components/Tools.jsx
> +	}
Worth considering a standard format like [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) with year-month-day?

For example:

```suggestion
	function getFormattedDateTime() {
		return new Date().toISOString().split('.')[0].replace(/[T:]/g, '-');
	}
```

Which gives:

```
2021-09-20-09-49-38
```

It's generally easier to sort/parse filenames in this format because sorting by name also sorts by date.

2021-09-23 15:16 UTC, nickcernis commented
@matthewguywright Welcome back! Just pinging in case you hand't seen the review comments above here. (Please feel free to ignore this if you had!)

2021-09-23 16:04 UTC, matthewguywright commented on includes/settings/scss/_buttons.scss
> +		border: 1px solid lighten($color-blue-dark, 10%) !important;
Updated

2021-09-28 08:43 UTC, nickcernis approved these changes, later dismissed
Looking good — nice work!

I explored e2e tests with Codeception to verify the downloaded file using the [Filesystem module](https://codeception.com/docs/modules/Filesystem), but I couldn't figure out a way to set a download path for Chrome that worked on Circle and locally. I'm happy to skip this for now.

2021-10-07 11:40 UTC, nickcernis approved these changes

2021-10-07 12:17 UTC, mindctrl approved these changes

2021-10-07 14:04 UTC, ChrisWiegman approved these changes
I finally got to review this this morning and could find no other issues. Well done!

2021-10-07 15:44 UTC, merged