[BH-1195] Enable reverse relationships
wpengine/atlas-content-modeler pull request #276
Opened 2021-09-17 13:54 UTC by ChrisWiegman

## Description

https://wpengine.atlassian.net/browse/

## Testing

## Screenshots

## Documentation Changes

## Dependant PRs

2021-09-27 08:27 UTC, nickcernis commented on includes/content-registration/custom-post-types-registration.php
> +					$name = $models[ $model ]['slug'] . '-' . $field['slug'] . '-' . $field['reverseSlug'];
Just noting that this results in a PHP warning if a relationships field was created before this PR: “Undefined index: reverseSlug”.

2021-09-27 09:12 UTC, nickcernis commented on includes/settings/js/src/components/fields/RelationshipFields.jsx
> +						/>
This field currently gets cleared if I:

1. Add a new relationship field.
2. Immediately click “Configure Reverse Reference” (without setting other fields such as, ”Name” and “API Identifier”).
3. Choose a model from the “Model To Reference” field.

I'm looking into the cause…

https://user-images.githubusercontent.com/647669/134879676-b614db20-f9c0-4235-853d-d189167fc64d.mp4

2021-09-27 09:35 UTC, nickcernis commented on includes/settings/js/src/components/fields/RelationshipFields.jsx
> +								clearErrors("reverseSlug");
`clearErrors` is not currently available here, so typing in the reverseName field generates errors at the moment. You can fix this by adding `clearErrors` to the `RelationshipFields` props at the top of `RelationshipFields.jsx` (it's already passed from `Form.jsx`):

```diff
const RelationshipFields = ({
	register,
	data,
	editing,
	watch,
	errors,
	setValue,
	model,
+	clearErrors,
}) => {
```

2021-09-27 11:50 UTC, ChrisWiegman commented on includes/content-registration/custom-post-types-registration.php
> +					$name = $models[ $model ]['slug'] . '-' . $field['slug'] . '-' . $field['reverseSlug'];
Good catch. I thought I had caught all those.

2021-09-27 11:55 UTC, ChrisWiegman commented on includes/content-registration/custom-post-types-registration.php
> +					$name = $models[ $model ]['slug'] . '-' . $field['slug'] . '-' . $field['reverseSlug'];
Fix pushed

2021-09-27 11:55 UTC, ChrisWiegman commented on includes/settings/js/src/components/fields/RelationshipFields.jsx
> +								clearErrors("reverseSlug");
Fix pushed

2021-09-27 14:25 UTC, nickcernis commented on includes/settings/js/src/components/fields/RelationshipFields.jsx
> +								: toValidApiId(models[model].plural)
Is `toValidApiId(models[model].plural)` the correct fallback value here if the reverse reference section is not open? Or should it be an empty string (because no value has been set)?

2021-09-27 14:27 UTC, nickcernis commented on includes/settings/js/src/components/fields/RelationshipFields.jsx
> +							readOnly={editing}
`readOnly={editing}` here means that I won't be able to set the `reverseSlug` if:

1. I create a relationship field but do not set “Configure Reverse Reference”.
2. I edit the relationship field.
3. I tick “Configure Reverse Reference”. At this point the reverseSlug is visible but not editable.

It might be that this is expected behavior, but just flagging in case we want to think about it some more.

2021-09-27 15:54 UTC, ChrisWiegman commented on includes/settings/js/src/components/fields/RelationshipFields.jsx
> +							readOnly={editing}
This is expected behavior. This is the big trade-off I was worried about. TBH, in graphQL this will actually make sense

2021-09-27 18:09 UTC, ChrisWiegman commented on includes/settings/js/src/components/fields/RelationshipFields.jsx
> +								: toValidApiId(models[model].plural)
Upon further review, yes, this is the intention as we need the slug here in a similar fashion as we talk about in your next comment.

2021-09-28 19:15 UTC, nickcernis commented on includes/settings/js/src/components/fields/RelationshipFields.jsx
> +						/>
I _think_ I have a fix for this in https://github.com/wpengine/atlas-content-modeler/pull/276/commits/2fcbb981fb02bb5d9b7b80c15a6661d13cd47dcb and https://github.com/wpengine/atlas-content-modeler/pull/276/commits/c6b4ed99f9b2db7bd5406d701d4bbd889e162ea8, but will do some more testing in the morning.

2021-09-29 15:23 UTC, nickcernis submitted a review, later dismissed

2021-09-29 15:48 UTC, nickcernis approved these changes

2021-09-29 15:49 UTC, nickcernis requested changes
Approved but then noticed failed tests…

2021-09-29 16:24 UTC, nickcernis approved these changes

2021-09-29 16:39 UTC, mindctrl approved these changes

2021-09-29 16:46 UTC, merged