BH-1189: author added to support with tests
wpengine/atlas-content-modeler pull request #316
Opened 2021-10-08 16:04 UTC by matthewguywright

## Description

Add 'author' to support in graphql.

2021-10-08 16:36 UTC, mindctrl requested changes
A few formatting things.

Also a test failed, but appears to be unrelated to what you've done here. Let's see if they pass after you make another commit here.

2021-10-08 17:37 UTC, ChrisWiegman submitted a review, later dismissed
Other than the issues John pointed out, this works fine for me. Approving while you solve the issues he has pointed out.

2021-10-11 17:46 UTC, mindctrl approved these changes

2021-10-11 18:35 UTC, ChrisWiegman approved these changes

2021-10-11 18:59 UTC, merged