BH-1184: add description to fields
wpengine/atlas-content-modeler pull request #323
Opened 2021-10-12 16:29 UTC by matthewguywright

## Description
Add description to fields in settings side and display on publisher side.

2021-10-13 09:56 UTC, nickcernis requested changes
I think we should remove the original description textarea from the Relationship field. It now has two descriptions with the changes from this PR.

The related `descriptionMaxLength` and `descriptionCount` logic for that field could also be removed from `includes/settings/js/src/components/fields/RelationshipFields.jsx`.

<img width="712" alt="Screenshot 2021-10-13 at 11 42 10" src="https://user-images.githubusercontent.com/647669/137110766-32e814ef-a593-4c12-b38b-1d1172c7f14f.png">

2021-10-13 10:48 UTC, nickcernis requested changes

2021-10-13 19:18 UTC, mindctrl requested changes

2021-10-14 16:37 UTC, nickcernis approved these changes

2021-10-14 17:01 UTC, mindctrl approved these changes
I think the description text is supposed to render with a color of `#405E6A`, if I'm reading the Figma file correctly, and these are not doing that. Otherwise this looks good.

2021-10-14 20:45 UTC, merged