[BH-1219] Ensure max ID size matches model name
wpengine/atlas-content-modeler pull request #332
Opened 2021-10-19 17:57 UTC by ChrisWiegman

## Description

This modifies the formatter we use for the slug to limit output to 20 characters.

https://wpengine.atlassian.net/browse/BH-1219

## Testing

No additional tests were necessary however the expected values of existing tests were modified to match the expected output.

2021-10-20 08:53 UTC, nickcernis requested changes
I don't think we can do this because of the 20 character limit in `register_post_type`:

https://github.com/WordPress/WordPress/blob/8447683474ebdee773fc4fca7b3e44dea45060f4/wp-includes/post.php#L1515-L1518

```php
	if ( empty( $post_type ) || strlen( $post_type ) > 20 ) {
		_doing_it_wrong( __FUNCTION__, __( 'Post type names must be between 1 and 20 characters in length.' ), '4.2.0' );
		return new WP_Error( 'post_type_length_invalid', __( 'Post type names must be between 1 and 20 characters in length.' ) );
	}
```

We should probably add a comment in our code to that effect, because I also tried to bump it to 50 at one point before @mindctrl stopped me. :-)

2021-10-21 13:04 UTC, nickcernis approved these changes

2021-10-21 13:10 UTC, ChrisWiegman commented
@nickcernis, good catch on the taxonomy issue. I hadn't realized we were reusing the function there. I'm going to approve this myself after testing your changes to it. Once we have @mindctrl or someone else, I think we'll be in good shape. Thanks!

2021-10-21 16:19 UTC, mindctrl approved these changes

2021-10-21 16:46 UTC, merged