[MTKA-1121] Add ability to set featured image using media field
wpengine/atlas-content-modeler pull request #346
Opened 2021-11-09 18:52 UTC by ChrisWiegman

## Description

https://wpengine.atlassian.net/browse/

## Testing

## Screenshots

## Documentation Changes

## Dependant PRs

2021-11-18 18:16 UTC, mindctrl requested changes
Seems to be working well. A few minor things I see in the first pass.

On another note, I thought we had decided to limit the media picker to images only, like the description of the field says in DevEx - "Limits media selection to image types". But I don't see it called out specifically in the AC in Jira.

2021-11-18 18:16 UTC, mindctrl commented on includes/publisher/class-publisher-form-editing-experience.php
> +						continue;
My editor is pointing out that `continue` isn't necessary as the last statement in a loop. Maybe this should be `break`?

2021-11-18 18:16 UTC, mindctrl commented on includes/publisher/class-publisher-form-editing-experience.php
> +	public function hide_screen_options( bool $show_screen, $screen ): bool {
We removed this function in https://github.com/wpengine/atlas-content-modeler/commit/670c80ae1a62b051b989ad8b92cf9647186424bc

Probably left over from when you originally branched off `main`?

2021-11-18 18:16 UTC, mindctrl commented on tests/acceptance/CreateContentModelMediaFieldCest.php
> +	public function i_can_add_a_featured_imag_emedia_field_to_a_content_model( AcceptanceTester $i ) {
```suggestion
	public function i_can_add_a_featured_image_media_field_to_a_content_model( AcceptanceTester $i ) {
```

2021-11-19 14:36 UTC, nickcernis commented on Makefile
> +COMPOSER_IMAGE   := -v "$$(pwd):/app" --user $$(id -u):$$(id -g) composer:1
Thanks for fixing this here!

2021-11-19 14:37 UTC, nickcernis commented on includes/publisher/lib/field-functions.php
> + * Determins if the field is the featured image or not.
```suggestion
 * Determines if the field is the featured image or not.
```

2021-11-19 14:40 UTC, ChrisWiegman commented on includes/publisher/class-publisher-form-editing-experience.php
> +	public function hide_screen_options( bool $show_screen, $screen ): bool {
Probably popped in while resolving merge conflicts. Fixed.

2021-11-19 14:42 UTC, ChrisWiegman commented on includes/publisher/class-publisher-form-editing-experience.php
> +						continue;
No notice in vscode but I've updated her anyway.

2021-11-19 14:54 UTC, nickcernis approved these changes, later dismissed
Working great. Confirmed adding, removing, changing fields, and the GraphQL and REST responses.

Thanks for your work on this, @ChrisWiegman!

<img width="587" alt="Screenshot 2021-11-19 at 15 52 59" src="https://user-images.githubusercontent.com/647669/142642813-399d28dd-4a8f-4421-b479-16c3dde91a17.png">

<img width="1391" alt="Screenshot 2021-11-19 at 15 51 16" src="https://user-images.githubusercontent.com/647669/142642435-c9a03841-a696-43c7-a9f7-5cdb90724b90.png">

2021-11-19 17:02 UTC, mindctrl commented on includes/publisher/class-publisher-form-editing-experience.php
> +					delete_post_thumbnail( $post ); // Delete first is innefficient but avoids werid behavior of set which otherwise treats an existing thumbnail as a bug.
'weird' is misspelled in the comment, but I wonder if the comment could be clearer? Is the bug that `set_post_thumbnail()` returns false if the value is the same as the one already stored in the db?

2021-11-19 17:03 UTC, mindctrl commented on includes/publisher/class-publisher-form-editing-experience.php
> +						/* translators: %s: atlas content modeler field slug */
Not sure it matters, but I think it's technically the model/post_type slug and not the field slug?

2021-11-19 18:21 UTC, mindctrl approved these changes

2021-11-19 18:37 UTC, merged