MTKA-1305: media repeatable
wpengine/atlas-content-modeler pull request #442
Opened 2022-02-22 18:24 UTC by matthewguywright

## Description

https://wpengine.atlassian.net/browse/

## Testing

## Screenshots

## Documentation Changes

## Dependant PRs

2022-02-22 18:40 UTC, anthonyburchell commented on includes/settings/js/src/components/fields/MediaFields.jsx
> +	const [showTitle, setShowTitle] = useState(data?.isTitle === true);
we wont need any concept of title for this one

2022-02-22 18:44 UTC, anthonyburchell commented on includes/settings/js/src/components/fields/MediaFields.jsx
> +						disabled={editing || showTitle}
here also you are checking for showtitle and editing

2022-02-25 05:39 UTC, anthonyburchell commented on includes/settings/js/src/components/fields/MediaFields.jsx
> +						defaultChecked={showRepeatable}
try changing this to `value={showRepeatable}` instead of defaultChecked

2022-03-09 14:10 UTC, mindctrl requested changes

2022-03-09 14:10 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +	if (field.isRepeatable && typeof field.isRepeatable === "boolean") {
```suggestion
	if (field.isRepeatableMedia && typeof field.isRepeatableMedia === "boolean") {
```

2022-03-09 14:10 UTC, mindctrl commented on includes/settings/js/src/components/fields/MediaFields.jsx
> +		data?.isRepeatable === true
```suggestion
		data?.isRepeatableMedia === true
```

2022-03-09 14:10 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +																<button
Should this be the TertiaryButton component instead of manually doing the button?

2022-03-09 14:10 UTC, mindctrl commented on includes/publisher/scss/_media-field.scss
> +.media {
Is there a reason we're doing scss files instead of Emotion here?

2022-03-09 14:16 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +
We can use the `acm-icons` alias when importing icons, like we do in other files. However, the TrashIcon is not imported and returned in the [`index.js` file](https://github.com/wpengine/atlas-content-modeler/blob/main/includes/components/icons/index.js), like all the others, so that one would need to be updated to work like the rest.

2022-03-09 14:18 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +	errors,
```suggestion
```

`errors` isn't being used.

2022-03-09 14:18 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +	defaultError,
```suggestion
```
```suggestion
```

`errors` and `defaultError` aren't being used.

2022-03-09 14:20 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +			const imgArr = [];
```suggestion
```

Not used

2022-03-09 14:21 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +																name="repeaters"
```suggestion
```
`name` is an invalid attribute on a `div`

2022-03-09 16:37 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +	if (field.isRepeatable && typeof field.isRepeatable === "boolean") {
@matthewguywright this `typeof field.isRepeatableMedia === "boolean"` check is what was breaking multi-select for me. The value of `field.isRepeatableMedia` is a string "true" instead of boolean true. Note that other properties use boolean values, so we should update this one to match.

![image](https://user-images.githubusercontent.com/1254870/157487168-a354fd03-ca35-471b-8dfe-264eed61ebac.png)

2022-03-10 16:50 UTC, matthewguywright commented on includes/publisher/scss/_media-field.scss
> +.media {
That's the pattern that's in place. It needs to be extracted from the scss and put into the repeatable fields if possible at some point.

2022-03-10 18:33 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +	const fileRegex = /\.(pdf|doc?x|ppt?x|pps?x|odt|sls?x|psd)$/i;
Where did this list of file extensions come from? What about .txt files? The way this is written, any file type that doesn't match something results in no icon. 

Screenshot
![image](https://user-images.githubusercontent.com/1254870/157731053-e62de9aa-4dab-443d-86bf-a206058c7b48.png)

What if we refactored it so that if there's no match for a specific type, it defaults to the file icon?

2022-03-10 19:34 UTC, mindctrl commented
Just noting we also need some tests here.

2022-03-11 14:33 UTC, matthewguywright commented on includes/publisher/js/src/components/MediaUploader.jsx
> +	const fileRegex = /\.(pdf|doc?x|ppt?x|pps?x|odt|sls?x|psd)$/i;
That works. The list comes from the WP allowable upload types for the media modal.

2022-03-11 14:59 UTC, matthewguywright commented on includes/publisher/js/src/components/MediaUploader.jsx
> +	const fileRegex = /\.(pdf|doc?x|ppt?x|pps?x|odt|sls?x|psd)$/i;
Txt files are not allowed by WP by default.

2022-03-12 07:31 UTC, Sameedahmad commented
media repeatable is really needed, Thank you @matthewguywright  for making it happen.

2022-03-21 15:00 UTC, nickcernis commented
@matthewguywright If you create a repeating media field with “use as featured image” ticked and save it on the publisher screen, do you see the error below (“There was an error updating the Array field data”)?

The message seems to be coming from the `if ( 'media' === $field_type` logic starting line 399 of `includes/publisher/class-publisher-form-editing-experience.php`. We probably need to adapt it to account for the fact that the posted values can now be an array of thumbnail IDs and not only a single ID. (Maybe use the first thumbnail ID as the featured image if there's an array of thumbnail IDs?)

<img width="989" alt="Screenshot 2022-03-21 at 15 54 58" src="https://user-images.githubusercontent.com/647669/159288182-ad6ba086-ccc5-4cba-bb7a-e5b15d23bdd5.png">

2022-03-21 15:04 UTC, andrewbotz commented on includes/components/icons/index.js
> +			return <TrashIcon />;
Trash Icon exists on line 67, should be able to remove one or the other.

2022-03-21 15:05 UTC, mindctrl commented
Noting conversation from Slack, when the repeating option is enabled, it does not disable/prevent the enabling of the featured image option — and vice versa.

2022-03-23 07:52 UTC, nickcernis commented on includes/settings/js/src/components/fields/Form.jsx
> +									disabled={!!isRepeatableMedia}
It looks like the parent div of this input field needs to change the class if `isRepeatableMedia` is true, so that the label gets ghosted when the checkbox is disabled:

```
							<div
								className={
									!!isRepeatableMedia && "read-only editing"
								}
							>
```

2022-03-23 07:52 UTC, nickcernis commented on includes/settings/js/src/components/fields/Form.jsx
> +									disabled={!!isRepeatableMedia}
It looks like the parent div of this input field needs to change the class if `isRepeatableMedia` is true, so that the label gets ghosted when the checkbox is disabled:

```
							<div
								className={
									!!isRepeatableMedia && "read-only editing"
								}
							>
```

2022-03-23 07:55 UTC, nickcernis commented on includes/settings/js/src/components/fields/MediaFields.jsx
> +				<div className={"field"}>
Same here — the class should change when the field is not editable so that the label is dimmed.

```suggestion
				<div
					className={
						isFeaturedWatcher ? "field read-only editing" : "field"
					}
				>
```

2022-03-23 07:55 UTC, nickcernis commented on includes/settings/js/src/components/fields/MediaFields.jsx
> +				<div className={"field"}>
Same here — the class should change when the field is not editable so that the label is dimmed.

```suggestion
				<div
					className={
						isFeaturedWatcher ? "field read-only editing" : "field"
					}
				>
```

2022-03-23 08:01 UTC, nickcernis commented on includes/settings/js/src/components/fields/MediaFields.jsx
> +						disabled={isFeaturedWatcher}
We should probably disable this when it's being edited to be consistent with the other “make repeatable” fields. (You can't change a field's repeatable status once it has been created.)

```suggestion
						disabled={editing || isFeaturedWatcher}
```

2022-03-23 11:01 UTC, nickcernis commented on tests/acceptance/CreateContentModelMediaFieldCest.php
> +		$i->seeElement( 'input[name="atlas-content-modeler[candy][positionxyz][0]"]:invalid' );
I think this test is failing because no field with a name of `atlas-content-modeler[candy][positionxyz][0]` exists until media has been selected from the media picker. (We only render the repeatable fields once a user has chosen media.)

If you apply the suggestion from Slack to render a hidden required input field when the user has not selected any media, you could then adapt this test to check for that field (by dropping the `[0]`):

```suggestion
		$i->seeElement( 'input[name="atlas-content-modeler[candy][positionxyz]"]:invalid' );
```

2022-03-23 11:07 UTC, nickcernis commented on tests/acceptance/CreateContentModelMediaFieldCest.php
> +		);
Same reason for the test failure here, I think: the element you're checking for doesn't exist until media has been selected.

You could check for something that is present instead? For example, instead of `seeElement()`:

```
$i->see( 'Manage Media', 'button[data-testid="media-uploader-manage-media-button"]' );
```

2022-03-23 14:38 UTC, nickcernis commented on tests/acceptance/CreateContentModelMediaFieldCest.php
> +		// Check that the first input in the index of available list items is rendering indicating a multiple being set.
@matthewguywright This comment no longer seems to apply with the change to the line below. Should we delete it?

2022-03-23 15:06 UTC, mindctrl commented on includes/publisher/js/src/components/MediaUploader.jsx
> +					{field?.required && <p className="required">*Required</p>}
The "Required" text should be translatable. Something like this (eyeballing this):
```suggestion
					{field?.required && <p className="required">*{__("Required", "atlas-content-modeler")}</p>}
```

2022-03-23 15:42 UTC, mindctrl requested changes
GraphQL queries on repeating media are causing WPGraphQL to freeze. The resolver needs an update, around line 541 or so in `custom-post-types-registration.php`.

```
					if ( $field['type'] === [ 'list_of' => 'MediaItem' ] ) {
						return array_map(
							function( $v ) use ( $context ) {
								return DataSource::resolve_post_object( (int) $v, $context );
							},
							$value
						);
					}
```

2022-03-23 16:15 UTC, nickcernis approved these changes

2022-03-23 16:21 UTC, mindctrl approved these changes

2022-03-23 17:41 UTC, merged