Add/repeatable number
wpengine/atlas-content-modeler pull request #445
Opened 2022-02-23 21:23 UTC by anthonyburchell

## Description
This PR adds settings and publisher side changes to the feature branch that will add repeatable number fields to ACM.

This PR is to get things in a solid state before the final feature branch merge.

2022-02-24 09:26 UTC, nickcernis commented on includes/publisher/scss/_number-field.scss
> +.number {
It might be good to put styling like this with the component itself using Emotion instead of adding more SCSS, but we could do it in a separate PR.

2022-02-24 09:35 UTC, nickcernis commented on includes/publisher/js/src/components/Number.jsx
> +											<>
We can remove the wrapping fragment here — it's only needed if you're returning multiple elements at the top level (we're only returning one <tr> here).

Removing it will helpfully get rid of the “Each child in a list should have a unique "key" prop” console warning (the `key` prop needs to be on the top-level element that's returning from `map`'s callback function — in this case we already have it on`<tr>` so removing the wrapping `<> </>` is enough).

2022-02-24 09:36 UTC, nickcernis commented on includes/publisher/js/src/components/Number.jsx
> +													<div
You can't use a `div` inside a `tr`, unfortunately, which is what this message in the console is warning:

```
Warning: validateDOMNesting(...): <div> cannot appear as a child of <tr>.
```

We'll have to either change the `tr` or the `div`.

2022-02-24 09:54 UTC, nickcernis commented on includes/publisher/js/src/components/Number.jsx
> +																defaultValue={
Using `defaultValue` and `value` on the same element with React generates this console warning:

> react-dom.js?ver=17.0.1:61 Warning: Number contains an input of type number with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://reactjs.org/link/controlled-components

You could copy the implementation from the `includes/publisher/js/src/components/Text.jsx` component (which removed `defaultValue` to use just `value` and `onChange`).

2022-02-25 05:40 UTC, anthonyburchell commented
Having a bit of a rough time with these e2e tests and jest failures. Will investigate again tomorrow.

2022-02-25 13:52 UTC, mindctrl commented on includes/publisher/js/src/components/Number.jsx
> +const { wp } = window;
```suggestion
```

Appears to be unused.

2022-02-25 13:53 UTC, mindctrl commented
The publisher screen isn't rendering for me. I get this error:

```Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.```

2022-02-28 15:30 UTC, mindctrl commented
Seeing these warnings:

`<div> cannot appear as a child of <tbody>`

`<button> cannot appear as a child of <tr>`

2022-03-01 10:11 UTC, nickcernis commented on includes/publisher/js/src/components/Number.jsx
> +												<div
Still seeing a warning due to use of div inside tr:

```validateDOMNesting(...): <div> cannot appear as a child of <tr>.```

You could put a `<td>` immediately inside the parent `<tr>` and move all current contents of the `<tr>` into the `<td>` to resolve this, although it may need some styling tweaks.

2022-03-01 14:34 UTC, anthonyburchell commented on includes/publisher/js/src/components/Number.jsx
> +												<div
ah yeah. That's what I did in this one and i accounted for the style changes. Not sure why I'm not seeing these warnings on my local but I'll fix it really quick.

2022-03-01 14:34 UTC, anthonyburchell commented on includes/publisher/js/src/components/Number.jsx
> +												<div
[fixes table structure and add button markup for hover states](https://github.com/wpengine/atlas-content-modeler/pull/445/commits/55ced17f4ab0f75b0f87608c1095097694b4ec85)

2022-03-01 14:50 UTC, anthonyburchell commented on includes/publisher/js/src/components/Number.jsx
> +												<div
Fixed now in https://github.com/wpengine/atlas-content-modeler/pull/445/commits/b52f955c0e9790d947a579e055bc963fce15d18c

2022-03-01 16:18 UTC, nickcernis approved these changes, later dismissed
Working great! Nice job! 🎉

2022-03-01 19:53 UTC, mindctrl requested changes
Left a few small comments, but this is working great! 😎

2022-03-01 19:53 UTC, mindctrl commented on includes/publisher/js/src/components/Number.jsx
> +															name="repeaters"
My editor flagged `name` as an attribute not allowed on a `div`.

2022-03-01 19:53 UTC, mindctrl commented on includes/publisher/js/src/components/Number.jsx
> +	if (field.isRepeatableNumber) {
Is this going to cause JS errors on existing fields that don't have `isRepeatableNumber` saved in the field config yet?

`field?.isRepeatableNumber` would address that, I think.

2022-03-01 19:53 UTC, mindctrl commented on includes/settings/js/src/components/fields/NumberFields.jsx
> +						name="isRepeatableNumber"
Nick briefly explained why you went with `isRepeatableNumber` here instead of `isRepeatable` like the Text field does. It might be worth adding a note here explaining why, for our future selves.

2022-03-01 19:53 UTC, mindctrl commented on includes/settings/js/src/components/fields/NumberFields.jsx
> +import React, { useContext, useState } from "react";
```suggestion
import React, { useState } from "react";
```

Appears that `useContext` isn't used here.

2022-03-01 19:53 UTC, mindctrl commented on includes/settings/js/src/components/fields/NumberFields.jsx
>  import { sprintf, __ } from "@wordpress/i18n";
```suggestion
import { __ } from "@wordpress/i18n";
```

Already existed, but while we're removing the unused import above it...

2022-03-01 21:17 UTC, mindctrl approved these changes

2022-03-02 13:52 UTC, merged