Fix issue where fatal errors happen on leading number model names
wpengine/atlas-content-modeler pull request #460
Opened 2022-03-14 13:49 UTC by anthonyburchell

This PR uses the toValidApiId format for generating a slug. Previously using a leading number in a slug name would cause fatal errors on the site. toValidAPiId factors in this limitation.

2022-03-14 14:08 UTC, nickcernis commented on includes/settings/js/src/components/CreateContentModel.jsx
> +import { toSanitizedKey, toValidApiId } from "../formats";
It looks like `toSanitizedKey` is an unused import now, and could be removed here.

```suggestion
import { toValidApiId } from "../formats";
```

2022-03-14 14:12 UTC, nickcernis approved these changes
Working well for me — I tested auto-generated model slugs and manually editing the slug and wasn't able to introduce a leading number either way.

Just one comment about an unused import, and the changelog conflict to fix up!

2022-03-14 14:42 UTC, nickcernis requested changes
In Slack we found that the name and plural names also need leading numbers to be stripped. Changing my review so we don't merge in error.

2022-03-15 21:25 UTC, anthonyburchell commented
closing in favor of: https://github.com/wpengine/atlas-content-modeler/pull/463

2022-03-15 21:25 UTC, closed without merging