add crud fetch model function
wpengine/atlas-content-modeler pull request #488
Opened 2022-04-01 14:28 UTC by anthonyburchell

This PR adds a fetch_model function to our api classes for the crud functionality.

2022-04-01 14:59 UTC, mindctrl requested changes

2022-04-01 14:59 UTC, mindctrl commented on includes/api/crud-functions.php
> +	$field = get_field_from_slug( $relationship_field_slug, get_option( 'atlas_content_modeler_post_types' ), $post->post_type );
```suggestion
	$field = get_field_from_slug( $relationship_field_slug, get_registered_content_types(), $post->post_type );
```

2022-04-01 14:59 UTC, mindctrl commented on includes/api/crud-functions.php
> +	$field = get_field_from_slug( $relationship_field_slug, get_option( 'atlas_content_modeler_post_types' ), $post->post_type );
```suggestion
	$field = get_field_from_slug( $relationship_field_slug, get_registered_content_types(), $post->post_type );
```

2022-04-01 15:47 UTC, anthonyburchell commented on includes/api/crud-functions.php
> +	$field = get_field_from_slug( $relationship_field_slug, get_option( 'atlas_content_modeler_post_types' ), $post->post_type );
@rfmeier fyi ^

I think this code got merged in a strange way as Ryan and I were working separately toward the feature branch. this was merged but I agree with the change. How should we best do this Ryan? okay to include in this PR?

2022-04-01 18:32 UTC, mindctrl commented on includes/api/crud-functions.php
> +	$field = get_field_from_slug( $relationship_field_slug, get_option( 'atlas_content_modeler_post_types' ), $post->post_type );
If it's annoying to do now, we can do this in another branch or during the final PR review

2022-04-01 18:37 UTC, mindctrl commented
There's a merge conflict here. I think if you resolve that, the diff view will look a lot cleaner and only show what you're adding in this PR.

2022-04-01 19:36 UTC, rfmeier commented on includes/api/crud-functions.php
> +	$field = get_field_from_slug( $relationship_field_slug, get_option( 'atlas_content_modeler_post_types' ), $post->post_type );
Either way works. A follow-up PR shouldn't require much effort.

2022-04-01 20:43 UTC, rfmeier requested changes

2022-04-01 20:43 UTC, rfmeier commented on includes/api/crud-functions.php
> +		return [];
Should the invalid return be `null` instead of an array? I know the model is an array, but technically an object. Arrays usually imply a list of.

2022-04-04 16:59 UTC, anthonyburchell commented on includes/api/crud-functions.php
> +		return [];
good call. done.

2022-04-04 17:58 UTC, rfmeier approved these changes

2022-04-04 18:35 UTC, mindctrl approved these changes

2022-04-04 18:37 UTC, merged