[MTKA-1359] Register ACM fields for GraphQL mutations
wpengine/atlas-content-modeler pull request #499
Opened 2022-04-14 15:48 UTC by nickcernis

## To-do
- [ ] Look into extracting repeated logic.
- [ ] Tests.
- [ ] Docs.

## Description

Work in progress to register ACM fields for `create[ModelName]` and `update[ModelName]` GraphQL mutations.

Allows devs to create and update ACM entries via WPGraphQL mutations like this one, where the rabbit model includes a `richText` and `repeatingText` field:

```
mutation CREATE_RABBIT {
  createRabbit(
    input: {
      clientMutationId: "CreateRabbit"
      name: "New Rabbit"
      status: PUBLISH
      richText: "test"
      repeatingText: ["a", "b", "c"]   
    }
  ) {
    rabbit {
      id      
      title
      date 
      repeatingText
      richText      
    }
  }
}
```

https://wpengine.atlassian.net/browse/

## Testing

## Screenshots

## Documentation Changes

## Dependant PRs

2022-04-19 17:00 UTC, nickcernis commented on includes/content-registration/custom-post-types-registration.php
> -
I updated `map_html_field_type_to_graphql_field_type` to return the correct type in place of this logic.

The GraphQL mutations logic also needs to grab the type so we may as well return it up front instead of changing it here.

2022-04-19 17:06 UTC, nickcernis commented on includes/publisher/lib/field-functions.php
> +			return [ $value ];
This change accounts for the fact that multiple choice fields can be passed as `[  [ 'choice1' => 'choice1', 'choice2' => 'choice2 ] ]` when sent via the web form, but as `[ 'choice1', 'choice2' ]` when sent as WPGraphQL mutation input.

2022-04-19 17:08 UTC, nickcernis commented on tests/integration/api-validation/test-data/posts.php
> +	update_post_meta( $post_id, 'booleanRequired', 'on' );
Boolean values are ultimately stored in meta as 'off' or 'on' and not 'true' or 'false' so I changed the tests to reflect that.

2022-04-19 17:09 UTC, nickcernis commented on tests/integration/api-validation/test-graphql-model-data.php
> +	public function test_graphql_delete_mutations_remove_acm_entries(): void {
I can omit this test if needed because it's WPGraphQL and not ACM that registers CPTs for delete mutations. I felt it worthwhile just to confirm and document delete mutation behavior, though.

2022-04-19 18:08 UTC, nickcernis commented on includes/content-registration/custom-post-types-registration.php
> +			return $meta_value === 'on' ? true : false;
Updating the REST response for consistency with the GraphQL response for boolean fields, and so that tests pass with the updated test data (which changed to 'on' and 'off' instead of 'true' and 'false').

2022-04-27 14:22 UTC, mindctrl requested changes
I left one minor nit/question. Excellent work!

2022-04-27 14:46 UTC, nickcernis commented on includes/content-registration/custom-post-types-registration.php
> + * @param string|array|null $field_type The HTML field type.
Well spotted, corrected in [d3b6e04](https://github.com/wpengine/atlas-content-modeler/pull/499/commits/d3b6e0494954f9b0890a4d6d0682a3680857be7c).

2022-04-27 15:08 UTC, mindctrl approved these changes, later dismissed

2022-04-27 15:50 UTC, mindctrl commented
@nickcernis there's a merge conflict here now. Sorry about that.

2022-04-27 16:37 UTC, nickcernis commented
@mindctrl Fixed, thanks for the note!

2022-04-28 12:55 UTC, mindctrl submitted a review, later dismissed

2022-04-28 14:55 UTC, matthewguywright commented on CHANGELOG.md
> +- Pressing enter in a repeating number, date or single line text field now moves focus to the next field, or adds a new field if focus is in the last field.
This is in ###Changed twice. Focus now moves... and also Pressing enter...

2022-04-28 15:03 UTC, nickcernis commented on CHANGELOG.md
> +- Pressing enter in a repeating number, date or single line text field now moves focus to the next field, or adds a new field if focus is in the last field.
@matthewguywright Thank you, well spotted! Fixed in [859b1aa](https://github.com/wpengine/atlas-content-modeler/pull/499/commits/859b1aa85fd0358b171f8224f3f1cfb58e285e67).

2022-04-28 15:04 UTC, matthewguywright approved these changes

2022-04-28 15:05 UTC, mindctrl approved these changes

2022-04-29 16:23 UTC, merged