Initial CRUD/API functions
wpengine/atlas-content-modeler pull request #503
Opened 2022-04-19 18:34 UTC by rfmeier

## Description

This pull request adds the initial CRUD/API functions. These functions can assist with external plugins working with Content Model entries.
- insert_entry_model()
- update_model_entry()
- replace_relationship()
- add_relationship()
- get_relationship()
- fetch_model()
- fetch_model_field()

2022-04-20 13:11 UTC, nickcernis commented on CHANGELOG.md
> +- Function update_model_entry() for updating and existing entry model and fields.
nit: typos

```suggestion
- Function insert_entry_model() for inserting a model entry and fields.
- Function update_model_entry() for updating an existing entry model and fields.
```

2022-04-20 13:13 UTC, nickcernis commented on includes/api/crud-functions.php
> +use function WPE\AtlasContentModeler\API\Utility\get_data_for_fields;
Looks like `get_data_for_fields` is unused in this file.

2022-04-20 13:26 UTC, nickcernis commented on includes/api/crud-functions.php
> +	$post_data = get_post( $post_id );
Should this be named something else, such as `$original_post_data` (with some extra logic to merge it with the passed in `$post_data`)? 

As spotted by @mindctrl, the function accepts a `$post_data` parameter, presumably to provide optional post data to update separately from the field data, but we're immediately overriding it here with the original data from `get_post`, so post data from the user gets ignored.

The tests in `test-crud-functions.php` always pass an empty array for as the third argument, so we don't validate that post data can be updated separately to field data.

2022-04-20 13:28 UTC, nickcernis commented on tests/integration/api/test-crud-functions.php
> +		$model_schema = $this->content_models['validation'];
`$model_schema` appears to be unused in this test.

2022-04-20 14:04 UTC, rfmeier commented on includes/api/crud-functions.php
> +use function WPE\AtlasContentModeler\API\Utility\get_data_for_fields;
Ah yes. Good catch. Thank you.

2022-04-20 14:07 UTC, rfmeier commented on includes/api/crud-functions.php
> +use function WPE\AtlasContentModeler\API\Utility\get_data_for_fields;
The function `array_get_key_value()` also existed, but wasn't being used. Removed this.

2022-04-20 14:11 UTC, rfmeier commented on includes/api/crud-functions.php
> +	$post_data = get_post( $post_id );
Now I see it `$post_data = get_post( $post_id );`. Yeah-- This is definitely overriding. I don't think it was intentional.

2022-04-20 14:20 UTC, rfmeier commented on CHANGELOG.md
> +- Function update_model_entry() for updating and existing entry model and fields.
Thanks.

2022-04-20 14:28 UTC, nickcernis reviewed
Great work, @anthonyburchell and @rfmeier!

Dropped a couple of notes above, but this is looking really good. I made a quick plugin in `wp-content/plugins/test.php` to try it out as WP plugin devs might.

```php
<?php
/* Plugin Name: Test */

namespace WPE\Test;

use function WPE\AtlasContentModeler\API\insert_model_entry;
use WPE\AtlasContentModeler\Validation_Exception;

add_action( 'wp_loaded', __NAMESPACE__ . '\test' );

function test() {
	// error_log( 'inserting bunny' );
	$field_data = [
		'name' => 'Bunny from the API',
	];

	// $field_data = [];
	
	$post_data = [
		'post_status' => 'publish',
	];	
	
	$skip_validation = false;

	$new_entry = insert_model_entry(
		'rabbit',
		$field_data,
		$post_data,
		$skip_validation		
	);
		
	// error_log( print_r( $new_entry, true ) );	
}
```

The rabbit factory works smoothly on page refresh. 🐰  🐰  🐰 

<img width="466" alt="Screenshot 2022-04-20 at 16 12 47" src="https://user-images.githubusercontent.com/647669/164250313-42b6c154-1c86-4d75-a3f8-e130c1696fea.png">

And returns errors if I pass `[]` as `$field_data`:

```
[20-Apr-2022 14:25:36 UTC] WP_Error Object
(
    [errors] => Array
        (
            [invalid_model_field] => Array
                (
                    [0] => Name field is required
                )

        )

    [error_data] => Array
        (
        )

    [additional_data:protected] => Array
        (
        )
)
```

2022-04-20 14:43 UTC, nickcernis commented on includes/api/crud-functions.php
> +	$post_data = get_post( $post_id );
Nice, looks fixed as of [3a1d6d1](https://github.com/wpengine/atlas-content-modeler/pull/503/commits/3a1d6d12516c3a50abe8bd59af3d2a4f06d084ef).

2022-04-20 14:44 UTC, nickcernis submitted a review, later dismissed

2022-04-21 13:16 UTC, mindctrl commented on includes/api/validation-functions.php
> +		validate_array( $value, "{$field['name']} must be an array of {$field['type']}" );
This verifies that the value is an array, but doesn't verify that the array values are numbers. You can pass an array of strings and it validates fine.

2022-04-21 13:58 UTC, rfmeier commented on includes/api/validation-functions.php
> +		validate_array( $value, "{$field['name']} must be an array of {$field['type']}" );
That is correct. During discussion it was agreed that we wouldn't validate the contents in the array of a repeatable field value... yet. There is currently a ticket to validate the contents of a repeatable field.

2022-04-21 14:04 UTC, mindctrl requested changes

2022-04-21 14:57 UTC, rfmeier commented on CHANGELOG.md
> +- Function fetch_model_field() to retrieve the model field schema.
Consistency is king. @anthonyburchell any thoughts about replacing `fetch_` with `get_` ?

2022-04-21 14:59 UTC, rfmeier commented on includes/publisher/lib/field-functions.php
> +		$repeatable = ( true === $field[ $key ] || 'true' === $field[ $key ] );
>Have we mixed those in our schema data?

Yes. It has been inconsistent.

2022-04-21 15:26 UTC, rfmeier commented on includes/publisher/lib/field-functions.php
> +		$repeatable = ( true === $field[ $key ] || 'true' === $field[ $key ] );
I was seeing values within field data arrays where there is a mix of `'true'` and `true`. This was to make up for that inconsistency.

2022-04-21 17:28 UTC, anthonyburchell commented on CHANGELOG.md
> +- Function fetch_model_field() to retrieve the model field schema.
agreed. 👍

2022-04-21 18:29 UTC, mindctrl approved these changes

2022-04-21 18:56 UTC, merged