MTKA-1488: blueprint local file upload
wpengine/atlas-content-modeler pull request #528
Opened 2022-05-10 15:56 UTC by matthewguywright

## Description

What changed and why?
Updated get remote blueprint to check for the path and use local or remote function accordingly.

Link to the JIRA ticket if available.
[https://wpengine.atlassian.net/browse/MTKA-1448](https://wpengine.atlassian.net/browse/MTKA-1448)

## Testing
Added tests for local file ZIP type and for empty contents.

## Documentation Changes
Updated verbiage for blueprint cli.

2022-05-10 16:03 UTC, nickcernis commented on tests/integration/blueprints/test-blueprint-downloads.php
> +		self::assertSame( 'application/zip', mime_content_type( $blueprint ) );
This is the cause of the test failure.

We could try getting the mime type from the file contents in one of the ways suggested here: https://stackoverflow.com/questions/4671672/how-to-get-the-mime-type-of-a-file-after-using-file-get-contents-from-a-remote-s

2022-05-11 11:28 UTC, nickcernis commented on tests/integration/blueprints/test-blueprint-downloads.php
> +		self::assertSame( 'application/zip', mime_content_type( $blueprint ) );
@matthewguywright This is working locally for me:

```php
public function test_get_local_blueprint_returns_valid_zip_file(): void {
		if ( ! defined( 'FS_METHOD' ) ) {
			define( 'FS_METHOD', 'direct' ); // Allows direct filesystem copy operations without FTP/SSH passwords. This only takes effect during testing.
		}

		$blueprint = get_local_blueprint( __DIR__ . '/test-data/acm-rabbits.zip' );
		$this->assertNotWPError( $blueprint );

		$file_info = new finfo( FILEINFO_MIME );
		$mime_type = $file_info->buffer( $blueprint );
		self::assertSame( 'application/zip; charset=binary',  $mime_type );
	}
```

2022-05-11 11:38 UTC, nickcernis commented
@matthewguywright Please could you add an entry to the changelog?

Apart from that and the test correction above this is looking good!

I found a couple of small docs things that seem worth updating too:

1. The WP-CLI synopsis and url here need the new synopsis and option (can copy the inline docs from the code where we renamed url to path):

https://github.com/wpengine/atlas-content-modeler/blob/c40dfcaa68734d366a9136f0ce80a42e573c78a6/docs/wp-cli/index.md?plain=1#L19-L28

2. The Blueprints doc here could be clarified to make it clear a local file path now works:

https://github.com/wpengine/atlas-content-modeler/blob/c40dfcaa68734d366a9136f0ce80a42e573c78a6/docs/blueprints/index.md?plain=1#L8

Perhaps:

> `wp acm blueprint import [url or path to zip file]` will import a blueprint from a publicly-accessible URL or local file.

…or whatever you think sounds best.

2022-05-11 13:44 UTC, mindctrl requested changes

2022-05-11 13:44 UTC, mindctrl commented on includes/blueprints/fetch.php
> +	}
Just a minor suggestion (from my editor) to reduce the nesting complexity a little.

```suggestion
	if ( filter_var( $path, FILTER_VALIDATE_URL ) ) {
		return get_remote_blueprint( $path );
	}

	return get_local_blueprint( $path );
```

2022-05-11 13:44 UTC, mindctrl commented on includes/blueprints/fetch.php
> +			esc_html__( 'Received empty response body.', 'atlas-content-modeler' )
This was leftover from the copy paste I think. Probably should read something like this. Anyone have a better suggestion for error text?

```suggestion
			esc_html__( 'File not found or not readable.', 'atlas-content-modeler' )
```

2022-05-12 08:24 UTC, nickcernis commented
@matthewguywright Please could you add an entry to the changelog?

2022-05-12 14:30 UTC, rfmeier approved these changes
Nice work! 👍

2022-05-12 14:39 UTC, anthonyburchell commented
This looks good and works great in my testing. I cant approve this PR but if I could I would 👍 lol

2022-05-12 14:42 UTC, anthonyburchell approved these changes
nvmd. I have the option. lol

2022-05-12 14:52 UTC, nickcernis approved these changes

2022-05-12 21:16 UTC, mindctrl approved these changes
Not sure why this still says I requested changes on this PR. Approving again and merging.

2022-05-12 21:20 UTC, merged