Mtka 1436 repeating constraints email
wpengine/atlas-content-modeler pull request #532
Opened 2022-05-13 14:36 UTC by andrewbotz

## Description

Add Advanced setting(s) for Email Repeatable that allows for min/max inputs of emails OR exact inputs of emails.

https://wpengine.atlassian.net/browse/MTKA-1436

## Checklist

I have:

- [x] Added Min/Max to email repeatable advanced settings
- [x] Added Exact to email repeatable advanced settings
- [x] Added ability to publish email repeatable with both Min/Max OR Exact email inputs with previously implemented validation (required, domains/subdomains, etc.)

## Testing

1. Create model with Email Repeatable that has advanced settings of Min/Max OR Exact
2. Publish using model with advanced min/max OR exact settings

**Notes**: when publishing, the end-user should only be able to add inputs that fit the criteria. Example, if the max repeatable is 5, then the end-user should not be able to add more inputs than the max. Same scenario for min and exact.

## Screenshots
<img width="516" alt="Screen Shot 2022-05-13 at 9 31 35 AM" src="https://user-images.githubusercontent.com/62450648/168306647-dc31f451-58e2-49ff-ae4d-c38dcfe90f52.png">
<img width="512" alt="Screen Shot 2022-05-13 at 9 31 17 AM" src="https://user-images.githubusercontent.com/62450648/168306651-994473df-8777-47fe-823c-890235ab7a44.png">
<img width="519" alt="Screen Shot 2022-05-13 at 9 31 46 AM" src="https://user-images.githubusercontent.com/62450648/168306655-7f31ee08-0a31-41b5-9505-895e3388c448.png">
<img width="503" alt="Screen Shot 2022-05-13 at 9 31 07 AM" src="https://user-images.githubusercontent.com/62450648/168306658-1d97aa81-2d98-4795-a6f4-eb08e822386a.png">

2022-05-16 16:33 UTC, matthewguywright commented on includes/settings/js/src/components/fields/EmailSettings.jsx
> +	const isMinMaxDisabled = getValues("exactRepeatable") || false;
You can use these here instead: !!
`const isMinMaxDisabled = !!getValues("exactRepeatable")`

2022-05-16 16:36 UTC, matthewguywright commented on tests/acceptance/AdvancedSettingsCest.php
> +		$i->clickWithLeftButton( '.field-list button.edit', -5, -5 );
This is interesting.

2022-05-16 16:36 UTC, matthewguywright approved these changes

2022-05-16 16:45 UTC, matthewguywright requested changes
I see errors being the same across all fields even if just one field has changed. It seems to be putting the same error in all locations.
<img width="605" alt="Screen Shot 2022-05-16 at 11 43 06 AM" src="https://user-images.githubusercontent.com/1815200/168642623-397529d5-d486-4502-832c-de073299adad.png">
.

I am also seeing errors that don't make sense, such as below there is content in the field but it's showing the domain is wrong. The domain is correct but the @ symbol is missing.
<img width="575" alt="Screen Shot 2022-05-16 at 11 46 59 AM" src="https://user-images.githubusercontent.com/1815200/168643222-08ead292-754f-4b3f-a7d5-689b8b484c9b.png">

2022-05-16 19:29 UTC, andrewbotz commented on tests/acceptance/AdvancedSettingsCest.php
> +		$i->clickWithLeftButton( '.field-list button.edit', -5, -5 );
Ya I need to shore up some of these e2e tests. This piece was copied from other tests -- it may not be needed anymore.

2022-05-20 14:32 UTC, matthewguywright approved these changes

2022-05-23 07:58 UTC, nickcernis approved these changes

2022-05-25 14:30 UTC, merged