MTKA-1473: bypass term insertion if it already exists for blueprint import
wpengine/atlas-content-modeler pull request #533
Opened 2022-05-16 16:25 UTC by matthewguywright

## Description

Skip term insertion if it already exists during blueprint zip import.

2022-05-16 18:18 UTC, anthonyburchell submitted a review, later dismissed
Looks good! 👍

2022-05-16 18:52 UTC, mindctrl requested changes

2022-05-16 18:52 UTC, mindctrl commented on includes/blueprints/import.php
> +			$term_already_exists = term_exists( $term['name'], $term['taxonomy'] );
I _think_ we need to pass the third argument to `term_exists()` to account for hierarchical terms. Something like this (untested):
```suggestion
			$term_already_exists = term_exists( $term['name'], $term['taxonomy'], $term['parent'] );
```
Note: you'd want to verify `$term['parent']` exists before using it, to avoid PHP notices. For example, note a few of our test terms lack the parent property (which is fine, but illustrates the need to check): https://github.com/wpengine/atlas-content-modeler/blob/d8461cfebe37352a6fb9e97b9340af4b50d0f4dd/tests/integration/blueprints/test-data/blueprint-good/acm.json#L169-L179

2022-05-17 09:19 UTC, nickcernis approved these changes, later dismissed
Looking good (pending John's suggested change)!

| Before | After |
| - | - |
| `> wp acm blueprint import https://raw.githubusercontent.com/wpengine/atlas-blueprint-portfolio/main/acm-blueprint.zip`<br>Fetching zip.<br>Unzipping.<br>Verifying ACM manifest.<br>Checking minimum versions.<br>Importing ACM models and fields.<br>Importing posts.<br>Importing terms.<br>Warning: Errors encountered during term import.<br>Warning: A term with the name provided already exists in this taxonomy.<br>Warning: A term with the name provided already exists in this taxonomy.<br>Warning: A term with the name provided already exists in this taxonomy.<br>Warning: A term with the name provided already exists in this taxonomy.<br>Warning: A term with the name provided already exists in this taxonomy.<br>Warning: A term with the name provided already exists in this taxonomy.<br>Warning: A term with the name provided already exists in this taxonomy.<br>Warning: A term with the name provided already exists in this taxonomy.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Warning: A term with the name provided already exists with this parent.<br>Tagging posts.<br>Importing media.<br>Importing post meta.<br>Restoring WordPress options.<br>Deleting zip and manifest.<br>Success: Import complete.<br> | `> wp acm blueprint import https://raw.githubusercontent.com/wpengine/atlas-blueprint-portfolio/main/acm-blueprint.zip`<br>Fetching zip.<br>Unzipping.<br>Verifying ACM manifest.<br>Checking minimum versions.<br>Importing ACM models and fields.<br>Importing posts.<br>Importing terms.<br>Tagging posts.<br>Importing media.<br>Importing post meta.<br>Restoring WordPress options.<br>Deleting zip and manifest.<br>Success: Import complete.<br> |

2022-05-17 16:06 UTC, mindctrl requested changes

2022-05-19 15:20 UTC, mindctrl requested changes
Looks good. Just need a changelog entry.

2022-05-19 16:14 UTC, mindctrl approved these changes

2022-05-19 16:17 UTC, merged