MTKA-1486: CRUD: validate min, max, step for Number field
wpengine/atlas-content-modeler pull request #559
Opened 2022-06-06 02:23 UTC by matthewguywright

## Description

Updated CRUD number field validation to include min, max, and step validation.

https://wpengine.atlassian.net/browse/MTKA-1486

## Checklist

I have:

- [X] Added an entry to CHANGELOG.md.

## Testing

Use CRUD functions to create a number field with invalid values for advanced settings to see errors.

2022-06-06 15:02 UTC, rfmeier requested changes

2022-06-07 10:26 UTC, nickcernis commented on includes/api/validation-functions.php
> +	if ( $number_type === 'integer' && ! is_int( $value ) ) {
I think this is why the tests are failing. You might have to check for integers in a string-safe way, because WP stores field data as strings:

```suggestion
	if ( $number_type === 'integer' && ! filter_var( $value, FILTER_VALIDATE_INT ) ) {
```

2022-06-07 14:12 UTC, rfmeier commented on includes/api/validation-functions.php
> +	if ( $number_type === 'integer' && ! is_int( $value ) ) {
@nickcernis is on the right path here. Since this could be submitted from a form, the value could be a string.

`filter_var` seems to work the best here. Although it does return `1` for `true`.

```
wp> filter_var( "1", FILTER_VALIDATE_INT )
=> int(1)
wp> filter_var( "1.2", FILTER_VALIDATE_INT )
=> bool(false)
wp> filter_var( "a", FILTER_VALIDATE_INT )
=> bool(false)
wp> filter_var( true, FILTER_VALIDATE_INT )
=> int(1)
```

But if `validate_number()` is ran before this, it should catch the possible `true` value.

2022-06-08 12:40 UTC, nickcernis submitted a review, later dismissed

2022-06-08 18:43 UTC, anthonyburchell submitted a review, later dismissed
This looks great @matthewguywright ! 🚀

2022-06-09 14:07 UTC, mindctrl commented
Just a note for @wpengine/mintaka that @rfmeier is taking over this PR and refactoring based on the other work he's been doing.

2022-06-13 07:21 UTC, nickcernis approved these changes

2022-06-13 14:47 UTC, rfmeier approved these changes

2022-06-13 14:47 UTC, merged