MTKA-1470 Crud documentation
wpengine/atlas-content-modeler pull request #568
Opened 2022-06-15 16:54 UTC by rfmeier

## Description

This pull request adds documentation for crud functions. Feel free to make any adjustments as there is a good change some of the descriptions could be worded more clearly.

## Checklist

I have:

- [ ] Added an entry to CHANGELOG.md.

2022-06-17 15:01 UTC, mindctrl requested changes
Looking good. A couple minor suggestions.

2022-06-20 09:31 UTC, nickcernis commented on docs/crud/index.md
> +The following examples with use a Rabbit model with an existing ID of `3`. The Rabbit model has  the following three fields.
Extra 'with':

```suggestion
The following examples use a Rabbit model with an existing ID of `3`. The Rabbit model has three fields:
```

2022-06-21 13:12 UTC, rfmeier commented on docs/crud/index.md
> +_description needed_
Thanks @nickcernis .

2022-06-21 13:33 UTC, mindctrl approved these changes

2022-06-21 13:39 UTC, nickcernis approved these changes

2022-06-21 14:01 UTC, merged