MTKA-1534: Add wp acm reset WP-CLI command
wpengine/atlas-content-modeler pull request #597
Opened 2022-07-18 13:56 UTC by nickcernis

## Description

https://wpengine.atlassian.net/browse/

## Checklist

I have:

- [ ] Added an entry to CHANGELOG.md.

## Testing

local/app/public 3s
> wp acm blueprint import https://raw.githubusercontent.com/wpengine/atlas-blueprint-portfolio/main/acm-blueprint.zip
Cannot load Zend OPcache - it was already loaded
Fetching blueprint.
Unzipping.
Verifying ACM manifest.
Checking minimum versions.
Importing ACM models and fields.
Importing posts.
Importing terms.
Tagging posts.
Importing media.
Importing post meta.
Restoring WordPress options.
Deleting zip and manifest.
Success: Import complete.

local/app/public 13s
> wp acm reset --yes
Cannot load Zend OPcache - it was already loaded
Deleting taxonomy terms.
Deleting ACM taxonomies.
Deleting relationship data.
Deleting posts.
Deleting media.
Deleting models.
Deleted: 17 posts, 12 media, 0 terms, 0 taxonomies, 0 relationships, Array models.
Success: ACM reset complete.

local/app/public
> wp acm reset --yes --all
Cannot load Zend OPcache - it was already loaded
Deleting taxonomy terms.
Deleting ACM taxonomies.
Deleting relationship data.
Deleting posts.
Deleting media.
Deleting models.
Deleted: 31 posts, 26 media, 0 terms, 0 taxonomies, 0 relationships, 0 models.
Success: ACM reset complete.

local/app/public
> wp acm reset --yes --all
Cannot load Zend OPcache - it was already loaded
Deleting taxonomy terms.
Deleting ACM taxonomies.
Deleting relationship data.
Deleting posts.
Deleting media.
Deleting models.
Deleted: 0 terms, 0 taxonomies, 0 relationships, 0 posts, 0 media, 0 models.
Success: ACM reset complete.

## Screenshots

## Documentation Changes

## Dependent PRs

2022-08-05 13:55 UTC, mindctrl requested changes

2022-08-05 13:55 UTC, mindctrl commented on includes/wp-cli/class-reset.php
> +			}
To avoid the second loop, like you did in `delete_media()`.
```suggestion
			}
			
			return;
```

2022-08-05 13:55 UTC, mindctrl commented on includes/wp-cli/class-reset.php
> +					'posts_per_page' => -1,
Noticed draft posts weren't deleted. This would handle that, unless we want to leave them around.

```suggestion
					'posts_per_page' => -1,
					'post_status'    => 'any',
```

2022-08-05 14:02 UTC, nickcernis commented on includes/wp-cli/class-reset.php
> +					'posts_per_page' => -1,
I think this might end up also deleting attachments as a side-effect, which we probably want to avoid for a delete posts function, but let me double check.

2022-08-05 14:03 UTC, nickcernis commented on includes/wp-cli/class-reset.php
> +			}
Do the `test_posts_are_reset` and `test_core_posts_are_reset` tests pass for you with this line? For me the tests were failing with this return statement. I think the second loop still needs to run to catch private ACM posts.

2022-08-05 14:38 UTC, mindctrl commented on includes/wp-cli/class-reset.php
> +			}
Yeah they fail for me too. I see why now that I've pulled it down and stepped through it.

2022-08-05 14:40 UTC, mindctrl commented on includes/wp-cli/class-reset.php
> +					'posts_per_page' => -1,
Sounds right, and not deleting drafts should be low impact. Let's leave it as is unless you see a clean way that doesn't complicate things.

2022-08-05 14:40 UTC, mindctrl submitted a review, later dismissed

2022-08-08 08:15 UTC, nickcernis commented
Fixed merge conflict, needs final re-review.

2022-08-08 12:27 UTC, mindctrl approved these changes

2022-08-08 12:39 UTC, merged